### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by opedge** [onnx/onnx-coreml#1]
I'm developing onnx-coreml converter https://github.com/prisma-ai/onnx-coreml. It is in the early experimental stage of development, but it supports all models from https://github.com/onnx/models. Maybe it could help you a bit if you are doing the similar thing?

**Comment by dzhulgakov** [comment]
Hi Oleg,

Yes, it's pretty awesome! CoreML support is something we wanted to build but haven't started yet. So contributions are very welcomed.

As for testing models from onnx/models - have you also compared the output results? One way would be to hook into some of the testing infra in onnx repo. You can see how it's done for onnx->caffe2 converter - that runs conversion and numerical comparison for models in the model zoo: https://github.com/onnx/onnx-caffe2/blob/master/onnx_caffe2/backend.py https://github.com/onnx/onnx-caffe2/blob/master/tests/onnx_backend_test.py

Also, are you interested in moving the code to this repo (onnx/onnx-coreml) eventually?

**Comment by opedge** [comment]
Hi @dzhulgakov ,

I tested all models from onnx zoo repo and compared output results: https://github.com/prisma-ai/onnx-coreml/blob/master/tests/test_models.py#L53
The results are almost equal with decimal=5. I think some small differences may occur due to different operators implementation in CoreML. I have experience with the same little difference and coreml in other projects, like torch2coreml for example.

I think this repo is the most suitable place for the onnx-coreml converter. It would be great if I could move the code here. Thank you!

**Comment by dzhulgakov** [comment]
Nice! Getting model tests passing is actually quite impressive (especially so that all implementations in CoreML are compatible).

For things which'd be nice to setup:
- tweak backend tests to interface like https://github.com/onnx/onnx-caffe2/blob/master/tests/onnx_backend_test.py for consistency (also takes care of downloading the models)
- setup CI (might be tricky as it'd require macos 10.13 and most services don't support it yet).

As for code - do you want to send PR against the repo? I can also see whether it'd be fine to just add you as a coowner.

Thanks a lot!

**Comment by opedge** [comment]
@dzhulgakov ,

- I'll tweak tests to be consistent with onnx-caffe2
- yes, it's tricky as macos 10.13 is not supported on the most services (like travis), but I'll try to find something suitable

I'd like to save copyright to prisma-ai if it is possible of course. It'd be great if you could add me as coowner. I plan to support more operators and make all necessary fixes for the new versions of ONNX library. We rely on these technologies for our internal development.

Thank you!

**Comment by dzhulgakov** [comment]
@opedge - I've granted you write access to this repo. Feel free to add code at you convenience. Thanks a lot for contributing!

As for CI - looks like some hosted Mac solutions already support 10.13 (e.g. https://www.macincloud.com/) We have some progress going on with Jenkins-based CI so might be able to use that.

**Comment by opedge** [comment]
@dzhulgakov Thank you! I added the current state of the project.
I tweaked backend tests to be consistent with onnx.backend.test. All model tests passed, but I temporary disabled node tests as CoreML don't support broadcasting, arbitrary dot operator, etc. Some of this issues could be resolved with shape inference for example (broadcast preprocessing), but some operators will stay unsupported, unfortunately.

As for CI – if you have Jenkins server installed, I can help with agent/job configuration. Do you prefer to use one CI server for all onnx projects, or you plan to decide which service to use on project level?
