### ISSUE TITLE
onnx-coreml doesn't support for python 3.x

### ISSUE THREAD

**Issue by tocean** [onnx/onnx-coreml#107]
I installed onnx-coreml using “pip install -U onnx-coreml” with python 3.5 successfully. But when I import the package in python, I got an error as bellows.

![image](https://user-images.githubusercontent.com/4133758/37503428-5fddb1ae-2913-11e8-8f5e-2960f9ed396b.png)

So could you like to build a wheel package supporting python 3.x and upload it to pypi?

**Comment by smessmer** [comment]
This is already fixed in the repository. You can install onnx-coreml using these commands:

    $ git clone https://github.com/onnx/onnx-coreml
    $ cd onnx-coreml
    $ pip install .

We're also planning to create a new pypi release.

**Comment by tocean** [comment]
I tried, but got an error about caffe2.python.onnx as bellows. I have installed 0.8.1 of caffe2 on my machine. Did that mean I should install the latest caffe2 from source? 
![image](https://user-images.githubusercontent.com/4133758/37566338-9d164654-2af2-11e8-8598-d57f6a2c328b.png)

What I expect is that I can install onnx-coreml using "pip install -U onnx-coreml" in python 3.x. So could you build a wheel package of version 0.0.2 suitable for python 3.x and upload it to [pypi](https://pypi.python.org/pypi/onnx-coreml/0.0.2)?

**Comment by smessmer** [comment]
Yes, you need to have caffe2 installed. We're working on removing that dependency, but right now it's still needed. As a shortcut, if you clone the repository including submodules, you can use the `install.sh` script, which should install caffe2 and onnx for you:

    $ git clone https://github.com/onnx/onnx-coreml --recursive
    $ cd onnx-coreml
    $ ./install.sh
