### ISSUE TITLE
ONNX node of type PRelu is not supported.

### ISSUE THREAD

**Issue by gi097** [onnx/onnx-coreml#131]
When converting a proto model, I get the following error: `TypeError: ONNX node of type PRelu is not supported.`, which is weird since the op is in the dictionary.
https://github.com/onnx/onnx-coreml/blob/0346a54f61b8ed46413314febf21c0e94bd598cf/onnx_coreml/_operators.py#L693
I am using the latest version on MacOS.

**Comment by gi097** [comment]
Here is the file I am trying to convert:
[export.onnx.zip](https://github.com/onnx/onnx-coreml/files/1845304/export.onnx.zip)

**Comment by aseemw** [comment]
Can you check again by installing the repo from the source as described in the readme file?
