### ISSUE TITLE
convert with Python 2-style str input fails

### ISSUE THREAD

**Issue by gustavla** [onnx/onnx-coreml#171]
If you put in a `str` object into `convert` in Python 2 (that is, a `bytes` object in Python 3 parlance), then this check fails:

```python
    if isinstance(model, Text):
        onnx_model = onnx.load(model)
```

https://github.com/onnx/onnx-coreml/blob/master/onnx_coreml/converter.py#L221-L222

```python
>>> model
'model.onnx.proto'
>>> isinstance(model, Text)
False
```
Unicode input works, so that is a work-around.

**Comment by bhushan23** [comment]
@gustavla do you still face the issue?
feel free to re-open
