### ISSUE TITLE
torch.nn.Parameter marked as not present

### ISSUE THREAD

**Issue by kilotaras** [onnx/onnx-coreml#324]
The following code will fail

```
class SampleModule(torch.nn.Module):
    def __init__(self):
        super(SampleModule, self).__init__()
        self.ones = torch.nn.Parameter(torch.ones(2, 3))

    def forward(self, x):
        return self.ones+x


def convert_sample():
    inpt = torch.rand(2,3)
    net = SampleModule()

    torch.onnx.export(net, inpt, '/tmp/sample.onnx', verbose=True)
    convert('/tmp/sample.onnx')
```

will produce 

```
graph(%0 : Float(2, 3)
      %1 : Float(2, 3)) {
  %2 : Float(2, 3) = onnx::Add(%1, %0), scope: SampleModule
  return (%2);
}

1/1: Converting Node Type Add
Traceback (most recent call last):
  File "prepare_coreml.py", line 117, in <module>
    convert_sample()
  File "prepare_coreml.py", line 110, in convert_sample
    mlmodel = convert('/tmp/sample.onnx')
  File "site-packages/onnx_coreml/converter.py", line 446, in convert
    mlmodel = MLModel(builder.spec)
  File "/site-packages/coremltools/models/model.py", line 153, in __init__
    self.__proxy__ = _get_proxy_from_spec(filename)
  File "site-packages/coremltools/models/model.py", line 77, in _get_proxy_from_spec
    return _MLModelProxy(filename)
RuntimeError: Error compiling model: "Error reading protobuf spec. validator error: Layer '2' consumes a layer named '1' which is not present in this network.".
```

I've hit this issue when trying to add CoordConv from recent uber's paper to some networks and the following is minimum example I could generate.

Moving `self.ones` to `forward` will change operation `%1` to `onnx::Constant` but leaves error the same.

`Add` is just an example.  The same problem is present with `torch.cat`, multiply and others.

**Comment by aseemw** [comment]
Seems like a bug in the converter. Will take a look.

**Comment by jalola** [comment]
I have similar issue to this whenever I try to use Constant Tensor and do a simple operator (e.g. Add, Div, Mul...)

Even though it could convert to coreml model without any error showing, but when I tried to import the model file to Xcode, Xcode shows similar error: 
`validator error: Layer 'class_inverse' consumes an input named '1' which is not present in this network.`

And here is the output of conversion from Pytorch --> onnx --> coreml
graph(%image : Float(1, 3, 299, 299)) {
  %1 : Float(1, 3, 299, 299) = onnx::Constant[value=<Tensor>](), scope: Sequential/ImageNorm[0]
  %class : Float(1, 3, 299, 299) = onnx::Div(%image, %1), scope: Sequential/ImageNorm[0]
  return (%class);
}

1/1: Converting Node Type Div

**Comment by aseemw** [comment]
Please try with PR#339

**Comment by jalola** [comment]
I pulled the master and it fixed this issue.

However, is there any reason that the constant converter does not support Constant Tensor with `len(shape)` > 3? I meant this: https://github.com/onnx/onnx-coreml/pull/339/commits/0ac96dbb3ffbb7209cc500fc6ee48e7cf8a39ea4#diff-0af2887bfd122ef3d6ad990a78c3ae13R997

**Comment by aseemw** [comment]
3 is the maximum length of the load constant layer in CoreML: https://github.com/apple/coremltools/blob/cf8c6dd710dc21fa2f2ab303f6729e9528997c01/mlmodel/format/NeuralNetwork.proto#L1582
