### ISSUE TITLE
Issue with converting LSTM pyTorch Model to ONNX to coreML

### ISSUE THREAD

**Issue by marcoleewow** [onnx/onnx-coreml#345]
If I convert an LSTM model with `num_layers=1`, it will give me:

> RuntimeError: Inferred shape and existing shape differ in rank: (4) vs (3)

If I convert an LSTM model with `num_layers=2`, it will give me:

> NotImplementedError: Unsupported ONNX ops of type: Gather,ConstantFill

I then implemented the custom parameters. It can compile to coreML model but now it gives me in XCode:

> validator error: Layer '31' of type 500 has 0 inputs but expects at least 1.

Here is the minimum test code, please send help!
https://gist.github.com/marcoleewow/2afb5762ed74f5244c9bd85eae35147d

**Comment by roozmahdavian** [comment]
Any luck with this? experiencing the same issues

**Comment by marcoleewow** [comment]
Apparently onnx-coreml still do not support RNNs. My workaround is to create an equivalent Keras model, transferred the weights manually and then used the official keras coreml converter.

**Comment by aseemw** [comment]
Yes, RNN support is broken currently in onnx-coreml converter, due to inability to handle gather layer, which is not supproted by CoreML, even though RNN/LSTM layers are. 

We will look into it. My guess is that updating the optimizer before conversion can get rid of the gather.

**Comment by steindor** [comment]
Having trouble converting a simple resnet34 from PyTorch b/c of missing Gather support. Tried using a the same custom conversion function as implemented by @marcoleewow but unfortunately get an error:

`Traceback (most recent call last):
  File "conv_pytorch.py", line 31, in <module>
    coreml_model = convert(model_proto, add_custom_layers=True, custom_conversion_functions={'Gather':convert_gather}, image_input_names=['inputImage'], image_output_names=['Prediction'])
  File "/anaconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/converter.py", line 458, in convert
    _convert_node(builder, node, graph, err)
  File "/anaconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1755, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/anaconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 443, in _convert_reshape
    "CoreML only supports Reshape layer when the target shape is static and known apriori")
  File "/anaconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_error_utils.py", line 71, in missing_initializer
    format(node.op_type, node.inputs[0], node.outputs[0], err_message)
ValueError: Missing initializer error in op of type Reshape, with input name = 342, output name = 350. Error message: CoreML only supports Reshape layer when the target shape is static and known apriori`

Any suggestions on bypassing this? Is there a support for Gather in the works? Seems difficult using PyTorch if one wishes to to convert the model to a CoreML model since it appears to be much easier with Keras.

**Comment by aseemw** [comment]
Gather is not supported in CoreML (Slice is). 

Sometimes gather can be mapped to a slice layer, in which case, I think onnx-converter can potentially translate it. 

Can you try PR #355 and see if it helps for your resent-34 model? There is a small optimization in that PR that removes a gather op if its input is a constant.

**Comment by MisonoMayu** [comment]
Im experiencing the same issues. Any idea on how to implement custom conversion functions?

**Comment by glenn-jocher** [comment]
I get the same error with Shape and Gather in **PyTorch 1.0.0 exporting to ONNX 1.3.0**:

Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/yolov3-tiny_onnx_to_coreml.py", line 208, in <module>
    main()
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/yolov3-tiny_onnx_to_coreml.py", line 32, in main
    yolov3_model = convert(model_proto, image_input_names=['0'], preprocessing_args={'image_scale': 1. / 255})
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/onnx_coreml/converter.py", line 455, in convert
    _check_unsupported_ops(graph.nodes)
  File "/Users/glennjocher/PycharmProjects/onnx/onnx-coreml/onnx_coreml/converter.py", line 143, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported ONNX ops of type: Shape,Gather

**Comment by iiSeymour** [comment]
I'd also like to convert a recurrent model and get running with CoreML.

> NotImplementedError: Unsupported ONNX ops of type: Gather, GRU

@aseemw does https://github.com/onnx/onnx-coreml/pull/412 help with getting GRU/LSTM conversion supported?

**Comment by aseemw** [comment]
Yes, with the new layers added in CoreML spec, GRU/LSTM conversion can be supported. 
However, more work is to be done in addition to the current PR #412 to fully support models with any new layer introduced in CoreML 3 (coremltools 3 beta release), as explained in the comment in PR #412. 

We are planning to do an update of the onnx converter for CoreML 3 (spec version 4).

**Comment by iiSeymour** [comment]
Good to hear it's on the roadmap, thanks @aseemw.

Until then, what is the recommended way forward for evaluating RNNs with CoreML *(keras)*?

**Comment by aseemw** [comment]
Yes, keras is definitely the most smooth route at the moment. 
There is also the beta tfcoreml converter that can handle recurrent networks (https://github.com/tf-coreml/tf-coreml#new-beta-tfcoreml-converter-with-core-ml-3). That too is under progress and undergoing improvements.

**Comment by iiSeymour** [comment]
@aseemw will GRUs with `linear_before_reset` set be supported?

**Comment by aseemw** [comment]
Hmm....can me point me to what ``linear_before_reset`` is?

**Comment by iiSeymour** [comment]
See the onnx description [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#GRU)

> When computing the output of the hidden gate, apply the linear transformation before multiplying by the output of the reset gate

**Comment by aseemw** [comment]
okay...yeah I'll have to double check if the GRU layer in CoreML spec has that option, even if it doesn't we should be able to build a GRU cell from control flow layers from scratch and implement it that way.

**Comment by iiSeymour** [comment]
@aseemw I'm looking at the tfcoreml converter and it doesn't seem to have any support for recurrent networks, am I looking in the correct [place](https://github.com/tf-coreml/tf-coreml/blob/master/tfcoreml/_ops_to_layers.py#L5)?

**Comment by iiSeymour** [comment]
The latest beta release now supports LSTMs, check it out.

@bhushan23 @aseemw GRUs next?

**Comment by marcoleewow** [comment]
LSTM pytorch model is now working! Follow this solution:

https://github.com/onnx/onnx-coreml/issues/458#issuecomment-528270062
