### ISSUE TITLE
Force output shape

### ISSUE THREAD

**Issue by yuvdar** [onnx/onnx-coreml#350]
https://github.com/onnx/onnx-coreml/blob/53d7c434037d23f28f48f23abf50d6574477d917/onnx_coreml/converter.py#L402

Is there any reason not always try and force an output shape?
If I have an output which is not an image, hence I don't want `image_output_names` to contain its name, but I still want to force the output shape, what should I do? (right now I put a non-existing output, which is an ugly hack I wish to remove)

**Comment by aseemw** [comment]
If output is not an image, it is not clear how to map the onnx shape to CoreML shape, at least at the beginning of the conversion process. For instance a rank 2 output could go to either (H,W) or (Seq,C) etc in CoreML. 

Currently this happens in a "soft" way here, output shape is mentioned in the description,
https://github.com/onnx/onnx-coreml/blob/53d7c434037d23f28f48f23abf50d6574477d917/onnx_coreml/converter.py#L530

During conversion, the dict `graph.onnx_coreml_shape_mapping` is populated (although it is not guaranteed to be filled), which is then used to infer CoreML shape from onnx shape. 

I think a change could be made, such that if the execution reaches this point (which means the output shape for CoreML can be inferred), 
https://github.com/onnx/onnx-coreml/blob/53d7c434037d23f28f48f23abf50d6574477d917/onnx_coreml/converter.py#L523
then this shape can be written in to the output shape field in the proto.

**Comment by aseemw** [comment]
I am closing this issue now. Please open it if there is a blocking issue.
