### ISSUE TITLE
ConvTranspose2d with groups doesn't work

### ISSUE THREAD

**Issue by kilotaras** [onnx/onnx-coreml#353]
The following code will fail

```python
model = torch.nn.ConvTranspose2d(4, 4, kernel_size=3, stride=2, output_padding=1, padding=1, groups=2)
input = torch.randn(1, 4, 8, 8)
torch.onnx.export(model, input, 'model.onnx', input_names=["input"], output_names=["output"])

mlmodel = convert('model.onnx')
mlmodel.save('model.mlmodel')
```

Looks like the problem is at https://github.com/onnx/onnx-coreml/blob/a8a63182831c3e415056db01b16eac93e562b156/onnx_coreml/_operators.py#L354

as weight shape will be different from output if you have groups, but I don't know internals of the library enough to fix it correctly.

**Comment by aseemw** [comment]
Yes there was a bug in the converter. PR #354 should resolve it.
