### ISSUE TITLE
Issue when using matmul

### ISSUE THREAD

**Issue by pavan4** [onnx/onnx-coreml#362]
Hello, 

I am trying to convert a pytorch model to coreml. It converts to onnx properly but when exporting to coreml I have the following error 

`Missing initializer error in op of type MatMul, with input name = <layer no>, output name = <layer no>. Error message: Second input to Matmul layer must be a constant`

my `forward` function looks like so

```
def forward(self, x, y):
    ...
    y_hat = torch.squeeze(torch.bmm(y_hat, y), 2)
    ...

```

The networks works properly with pytorch. I checked the code of `_operators.py` and it looks like `y` should be initialized as a `Variable` to be treated as a `constant`. However, that would hardcode the tensor input. Is there anyway to treat the y as an input from coreml? Or am I doing something wrong?

**Comment by aseemw** [comment]
Yes the other input must be a constant, thats the only mode supported by CoreML. 
You can look to use CoreML custom layers for any layer type that is not supported.

**Comment by SumatP** [comment]
I believe CoreML 3 supports this through the BatchedMatMulLayer. Is there an estimate of when onnx-coreml will support CoreML 3?

Also, custom layers to replace MatMul with this functionality currently don't work for me unless I rename the MatMul node to something else, this isn't a huge issue though.

**Comment by bhushan23** [comment]
@SumatP support for matmul is added
Could you please give a try to latest beta? https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3
Feel free to re-open if you still face issues
