### ISSUE TITLE
iOS ONNXLive Demo Black Screen

### ISSUE THREAD

**Issue by glenn-jocher** [onnx/onnx-coreml#363]
I am trying to run the iOS demo featured here:
https://pytorch.org/tutorials/advanced/ONNXLive.html

I build and run the app on my physical iPhone XS (iOS 12.1), I authorize the app to use the camera, and then I see Xcode debug error (out of memory). I notice the default CoreML models are set up for 1080 x 1080 size images, which is large, so I downsize to new 250 x 540 CoreML models per pytorch tutorial. Then I build and run again, no errors this time, but only a black screen shows on my iPhone, Xcode showing 95% GPU utilization for 15 minutes, no response from app, just black. Restarting and replugging iPhone and Xcode does not solve problem.

![screenshot 2018-12-05 at 13 45 18](https://user-images.githubusercontent.com/26833433/49514357-1a9ac900-f894-11e8-8aaa-e94da48eb6e2.jpg)

iPhone XS 12.1
Xcode 10.1

**Comment by aseemw** [comment]
Does the .mlmodel work fine when you call predict using coremltools in python?

**Comment by glenn-jocher** [comment]
The pytorch models work correctly, I had not tested them in python after export to .onnx and then .mlmodel.

I got it all working in the end by assigning the last layer name according to the Inputs and Outputs name that showed in Xcode for the mlmodel. I have no idea why, but the last layer is called '156', even though pytorch shows only 61 layers. I believe the conversion from pytorch to onnx creates some very arbitrarily strange layer names that then need to be discovered before the conversion to mlmodel.

**Comment by aseemw** [comment]
Yeah pytorch layers gets split into smaller mathematical ops, so thats not surprising. 

Please test in coremltools first, thats easier to debug than Xcode.
