### ISSUE TITLE
NotImplementedError: Unsupported ONNX ops of type: Shape,Tile

### ISSUE THREAD

**Issue by zhiyaoma** [onnx/onnx-coreml#364]
Now I am training my own model, maybe my line of code:
"mask = mask.repeat(1, 3, 1, 1)"
 can't be transferred from .onnx to .mlmodel
 Please update "onnx_coreml" as soon as possible

**Comment by aseemw** [comment]
CoreML does not support "Shape, Tile" layers so the converter cannot support them. For feature requests to CoreML framework, please file a bug at https://developer.apple.com/bug-reporting/ 

Did you try using the tip of master from this branch while converting your model? Some of the optimizations that have gone in recently, can get rid of these ops from the onnx model prior to conversion. 
If that doesn't work either, then you can look at using CoreML custom layers.

**Comment by bhushan23** [comment]
Support for Shape and Tile is added in CoreML 3
https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3

Closing.
