### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by glenn-jocher** [onnx/onnx-coreml#369]
I get this error message when trying to export the following yolov3-tiny.onnx model to CoreML which I originally exported from PyTorch 1.0 correctly. I am on a Python 2.7 venv and installed ONNX with `pip install -U onnx-coreml`. The ONNX model is here. Other ONNX models export without issue, but this one causes segmentation fault:
https://storage.googleapis.com/ultralytics/yolov3-tiny.onnx (35 MB)

- The pytorch model originates from https://github.com/ultralytics/yolov3, and operates correctly with no issues. 
- The ONNX model opens with the Netron viewer correctly, no issues there either. 

UPDATE: I get the same error installing from source and using CLI:
```bash
Glenns-MBP:weights glennjocher$ convert-onnx-to-coreml -o yolov3-tiny.mlmodel yolov3-tiny.onnx
Segmentation fault: 11
```

**Comment by bhushan23** [comment]
@glenn-jocher  could you please give a try to https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3 latest beta?
Feel free to re-open if you still face this issue
