### ISSUE TITLE
ReshapeInitTensorFuser in transformers removed a reshape layer in onnx model

### ISSUE THREAD

**Issue by dianxin556** [onnx/onnx-coreml#373]
when i transform the onnx model to coreml. I got an error like this:
`179/182: Converting Node Type Sub
Traceback (most recent call last):
  File "/home/dianxin/inpainting/pytorch-inpainting-with-partial-conv-master/onnx_to_coreml.py", line 11, in <module>
    coreml_model = convert(model_proto, image_input_names=['0'], image_output_names=['186'])
  File "/usr/local/lib/python2.7/dist-packages/onnx_coreml/converter.py", line 464, in convert
    _convert_node(builder, node, graph, err)
  File "/usr/local/lib/python2.7/dist-packages/onnx_coreml/_operators.py", line 1826, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/usr/local/lib/python2.7/dist-packages/onnx_coreml/_operators.py", line 247, in _convert_sub
    _convert_broadcast_op(builder, node, graph, err, "ADD")
  File "/usr/local/lib/python2.7/dist-packages/onnx_coreml/_operators.py", line 69, in _convert_broadcast_op
    ranks = [len(graph.onnx_coreml_shape_mapping[input_]) for input_ in node.inputs]
KeyError: u'326'`

when I check  graph.onnx_coreml_shape_mapping but not find  u'326'. Howerver, the onnx model graph has the reshape layer originally, like this:
` %319 : Tensor = onnx::Constant[value={171}]()
  %320 : Tensor = onnx::Mul(%318, %319)
  %321 : Float(1, 3, 256, 256) = onnx::Clip[max=1, min=0](%314), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  %322 : Float(1, 3, 256, 256) = onnx::Mul(%320, %321), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  %323 : Float(1, 19, 256, 256) = onnx::Mul(%311, %312), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  %324 : Float(1, 3, 256, 256) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%323, %75, %76), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  %325 : Tensor = onnx::Constant[value= 1  3  1  1 [ CPULongType{4} ]](), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  %326 : Float(1, 3, 1, 1) = onnx::Reshape(%76, %325), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  %327 : Float(1, 3, 256, 256) = onnx::Sub(%324, %326), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  %328 : Float(1, 3, 256, 256) = onnx::Mul(%327, %322), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  %329 : Float(1, 3, 256, 256) = onnx::Add(%328, %326), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  %330 : Float(1, 3, 256, 256) = onnx::Mul(%329, %321), scope: PConvUNet/PCBActiv[dec_1]/PartialConv2d[conv]
  return (%330, %321);
}`
 
%325 and %326 have been removed by ReshapeInitTensorFuser transformers.How should I do ?Thanks very much!

**Comment by bhushan23** [comment]
@dianxin556 please give a try to latest beta https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3
and feel free to re-open if you still face this issue
