### ISSUE TITLE
 Error message: {}\n".format(node.op_type, err_message, ) TypeError: Error while converting op of type: MatMul. Error message: CoreML incompatible axis placement

### ISSUE THREAD

**Issue by chinmaydas96** [onnx/onnx-coreml#375]
I am trying to convert a Pytorch model to .mlmodel. so I am first converting .pth file to .onnx file then .onnx file to .mlmodel file.

My Input size is : (1,3,299,299)

Here is my code for conversion:

    class DenseNet(nn.Module):
        def __init__(self):
            super(DenseNet, self).__init__()
            
            # get the pretrained DenseNet model
            densenet = models.densenet161(pretrained=True)
            
            # freeze the gradients to avoid training
            for i, param in enumerate(densenet.parameters()):
                param.requires_grad_(False)
            
            # transfer learning procedure
            # take everything before the 12th layer of the densenet
            modules = list(densenet.children())[0][:12]
            self.densenet = nn.Sequential(*modules)
            
            # transfer the classifier
            self.classifier1 = nn.Linear(in_features=2208, out_features=4096)
            self.classifier2 = nn.Linear(in_features=4096, out_features=2887)
            
            # relu activation
            self.prelu = nn.PReLU()
    
            # dropout
            self.dropout = nn.Dropout(p=0.5)
            
            # max pool
            self.avg_pool = nn.AvgPool2d(kernel_size=7)
            
        def forward(self, x):
            
            # get the features from the original VGG
            features = self.densenet(x)
            # flat the features
            features = self.avg_pool(features).squeeze()
            # out
            features = self.dropout(self.prelu(self.classifier1(features)))
            logits = self.classifier2(features)
            return logits
    
    
    def load_checkpoint(checkpoint_path):
        checkpoint = torch.load(checkpoint_path,map_location="cpu")
        model = DenseNet()
        model.load_state_dict(checkpoint)
        return model
    
    model = load_checkpoint('model.pth')
    dummy_input = torch.randn(1, 3, 299, 299, device='cpu')
    torch.onnx.export(model, dummy_input, "model_output.onnx")

This script is running successfully while .onnx to .mlmodel script gives me the error.

Here is the script that I am using :

    import sys
    from onnx import onnx_pb
    from onnx_coreml import convert
    
    model_in = 'model_output.onnx'
    model_out = 'model_output.mlmodel'
    
    model_file = open(model_in, 'rb')
    model_proto = onnx_pb.ModelProto()
    model_proto.ParseFromString(model_file.read())
    coreml_model = convert(model_proto)
    coreml_model.save(model_out)

This script is giving me the following errors :

> 570/574: Converting Node Type MatMul
Traceback (most recent call last):
  File "densenet.py", line 84, in <module>
    coreml_model = convert(model_proto)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/onnx_coreml/converter.py", line 458, in convert
    _convert_node(builder, node, graph, err)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1755, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1091, in _convert_matmul
    return err.unsupported_op_configuration(builder, node, graph, "CoreML incompatible axis placement")
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/onnx_coreml/_error_utils.py", line 56, in unsupported_op_configuration
    "Error while converting op of type: {}. Error message: {}\n".format(node.op_type, err_message, )
TypeError: Error while converting op of type: MatMul. Error message: CoreML incompatible axis placement

But when I change the dummy input size in pth to onnx model to 

> dummy_input = torch.randn(10, 3, 299, 299, device='cpu')

or any number greater than 1.It works prefectly fine. 
But I need the input to be single color image with size (299,299).

**Comment by calclavia** [comment]
I'm getting the same issue.  With an input of:
```
torch.rand(1, 5)
```

it works, but with 
```
torch.rand(1, 1, 5)
```

it will fail with the same error

**Comment by jbmaxwell** [comment]
What does the error actually mean? I'm having the same problem converting a VAE. It has an `nn.Linear()` at the top of the Decoder, which seems to be where it's hitting the error... ?

**Comment by aseemw** [comment]
what is the value of `mapp` when the error is encountered at https://github.com/onnx/onnx-coreml/blob/001679d3f006133706b47cdf02955133377f8298/onnx_coreml/_operators.py#L1134 ? 

CoreML tensors are laid down in static 5 shape : (Seq, Batch, C, H, W)
From free rank onnx vectors, the converters tries to determine a mapping to the CoreML shape.
For example: (10,3,4) can be mapped to say (10,3,4,1,1) or (1,1,10,3,4) etc

The CoreML inner_product (similar, but not equivalent to, onnx GEMM op) has constraints on what inputs it can operate on, which are being checked in around the line where the error occurs.

**Comment by jbmaxwell** [comment]
Well, I don't actually hit that error in `_convert_gemm`, it's in `_convert_matmul`, but the mapp is `[1, 2, 3, 4]`.

**Comment by aseemw** [comment]
is this the error you get when the code snippet you gave earlier is executed? 
What is the dimensions of the input tensor you give?

**Comment by jbmaxwell** [comment]
Yes, the error is the same as this thread: `Error while converting op of type: MatMul. Error message: CoreML incompatible axis placement`. The mapp is `[1, 2, 3, 4]`, printed right before the `else:` in the `_convert_matmul` function:

    if node.inputs[0] in graph.onnx_coreml_shape_mapping:
        mapp = graph.onnx_coreml_shape_mapping[node.inputs[0]]
        if mapp == [1,2] or mapp == [0,2]: #[B,C] or [S,C]
            _add_inner_product([node.inputs[0]], node.outputs, W=W, b=None, node=node, builder=builder)
        elif mapp == [3,4]: #[H,W]
            _add_transpose_before_after(_add_inner_product, [node.inputs[0]], node.outputs, [2,3,0,1],W=W, b=None, node=node, builder=builder)
        elif mapp == [2,3]: #(C,H)
            _add_transpose_before_after(_add_inner_product, [node.inputs[0]], node.outputs, [1,2,0,3],W=W, b=None, node=node, builder=builder)
        elif mapp == [2,4]: #(C,W)
            _add_transpose_before_after(_add_inner_product, [node.inputs[0]], node.outputs, [1,3,2,0], W=W, b=None, node=node, builder=builder)
        else:
            print('mapp: {}'.format(mapp))
            return err.unsupported_op_configuration(builder, node, graph, "CoreML incompatible axis placement")

During train/test the input size is `[64, 16]`, where 64 is my batch size and 16 is `z`. (I'm not sure how to print the size at the point of the error, I'm afraid.)

**Comment by aseemw** [comment]
The test added on PR #396 , based on your code snippet, works fine.

**Comment by jbmaxwell** [comment]
It will be about 30-45 mins, but I'll update this post when I've tried it.

**Comment by aseemw** [comment]
please see https://github.com/onnx/onnx-coreml#running-unit-tests

**Comment by bhushan23** [comment]
@chinmaydas96 please give a try with latest beta https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3
and feel free to re-open if you still face this issue
