### ISSUE TITLE
Error in re-declaring input when using multiple input

### ISSUE THREAD

**Issue by calclavia** [onnx/onnx-coreml#377]
When initializing an exported model in CoreML, I get the following error:

```
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=com.apple.CoreML Code=0 "Error in re-declaring input stateIn." UserInfo={NSLocalizedDescription=Error in re-declaring input stateIn.}
```

To replicate, simply create a linear model with TWO inputs and initialize in CoreML. A single input model works but once you add another input it crashes (e.g A GRUCell taking previous hidden state).

```
let model = MyModel()
```

**Comment by bhushan23** [comment]
@calclavia do you face issue with latest beta? https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3
feel free to re-open if you still see the error
