### ISSUE TITLE
Convert conv ops after reshape error

### ISSUE THREAD

**Issue by MisonoMayu** [onnx/onnx-coreml#381]
I am trying to convert a TCN model to CoreML and run into error like:

8/185: Converting Node Type Conv
Traceback (most recent call last):
  File "/opt/project/deepspeech.pytorch/onnx2coreml.py", line 12, in <module>
    coreml_model = convert(model_proto)#, image_input_names=['0'], image_output_names=['186'])
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/converter.py", line 464, in convert
    _convert_node(builder, node, graph, err)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1839, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 443, in _convert_conv
    builder, node, graph, err)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 198, in _add_conv_like_op
    "error in axes alignment between onnx and coreml")
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_error_utils.py", line 56, in unsupported_op_configuration
    "Error while converting op of type: {}. Error message: {}\n".format(node.op_type, err_message, )
TypeError: Error while converting op of type: Conv. Error message: error in axes alignment between onnx and coreml

Is conv1d not supported currently?

**Comment by aseemw** [comment]
It should work. see this test: https://github.com/onnx/onnx-coreml/blob/8a09c2c3a9ff6789f4dd35a12f5b8091f188f5b9/tests/model_test.py#L212

Can you produce a small unit test that reproduces the error?

**Comment by MisonoMayu** [comment]
Is it a bug with view()? even if I replace conv1d with conv2d I still get the same error
`                self.conv = torch.nn.Conv1d(64,
                                            out_channels,
                                            kernel_size=(1,kernel_size),
                                            stride=stride,
                                            padding=0,
                                            dilation=dilation,
                                            groups=groups,
                                            bias=bias)
`

**Comment by MisonoMayu** [comment]
I modified the dynamic reshape test
`
                self.conv = torch.nn.Conv1d(in_channels=300,
                                            out_channels=32,
                                            kernel_size=3,
                                            stride=1,
                                            padding=0,
                                            bias=True)

            def forward(self, x):
                x = x.view(1,300,100)
                x = self.conv(x)

                return x
`
and got the same error so I think the problem is reshape before conv

**Comment by MisonoMayu** [comment]
I also tried last after reshape and linear and they both worked fine.

**Comment by MisonoMayu** [comment]
And I modified _operators.py 
    elif len(target_shape) == 3:  # (C,H,W)
        coreml_shape = (
            1, target_shape[0], target_shape[1], target_shape[2]
        )
        if _is_input_shape_mapping_defined(node, graph):
            graph.onnx_coreml_shape_mapping[node.outputs[0]] = [2,3,4]
to
    elif len(target_shape) == 3:  # (C,H,W)
        coreml_shape = (
            1, target_shape[0], target_shape[1], target_shape[2]
        )
        if _is_input_shape_mapping_defined(node, graph):
            graph.onnx_coreml_shape_mapping[node.outputs[0]] = [1,2,0]
 don't think it's a good solution though

**Comment by mayokaze** [comment]
Hi, I just created a pr use my private account to fix this error.

**Comment by MisonoMayu** [comment]
It's solved in #382 , close for now.
