### ISSUE TITLE
New sequence lenght computation failed

### ISSUE THREAD

**Issue by Umity** [onnx/onnx-coreml#385]
Hi, i am trying to convert onnx model to coreml model but it is failing to do the job properly..

here is the error msg i am getting:

Translation to CoreML spec completed. Now compiling the CoreML model.
2019-02-09 00:12:44.835 python[5285:954976] IMPORTANT: new sequence length computation failed, falling back to old path. Your compilation was sucessful, but please file a radar on Core ML | Neural Networks and attach the model that generated this message.
Model Compilation done.
Input name(s) and shape(s): 
input.1 : (C,H,W) = (3, 1080, 1080) 
.

Any idea what may cause this? It still create the model file but not able to create appropriate evaluation parameters. eg, instead of image input, it creates MultiArray parameter.

**Comment by Umity** [comment]
And here is my onnx_to_coreml.py file:
import sys
from onnx import onnx_pb
from onnx_coreml import convert

model_in = sys.argv[1]
model_out = sys.argv[2]

model_file = open(model_in, 'rb')
model_proto = onnx_pb.ModelProto()
model_proto.ParseFromString(model_file.read())
coreml_model = convert(model_proto, image_input_names=['inputImage'], image_output_names=['outputImage'])
coreml_model.save(model_out)

**Comment by aseemw** [comment]
The error you get is just a warning, so you can safely ignore. 
Regarding the issue you are hitting, something else might be going on. 

For your original onnx model: what are the input and output names and their corresponding full shapes?

**Comment by Umity** [comment]
Hello Aseem, thank you so much. 

Well, that's a good question. First, I used a dataset that consist of 2500 around photos and it didnt give me any .pth model file. But it produced .model file. I tried to convert them to onnx and then coreml but it failed, the same fail as i told above. But then as a test, i downloaded some .pth files (candy.pth i used as a test) and it failed again. I mean, maybe not fail, but parameters are MultiArray (Float 32 3 x 1080 x 1080), not Image (Color 720 x 720). 

Here is my command when i am trying to convert to onnx:
python neural_style/neural_style.py eval --content-image /mypath/images/content-images/amber.jpg --model /mypath/saved_models/candy.pth --output-image /mypath/images/content-images/amber1.jpg --cuda 0 --export_onnx /mypath/models/pytorch_model2a.onnx

Am I doing something wrong when trying to convert to .onnx file?

**Comment by aseemw** [comment]
in your code snippet above you mentioned 
`coreml_model = convert(model_proto, image_input_names=['inputImage'])`
however, if you look at the .onnx file (you can visualize it in [netron](https://github.com/lutzroeder/netron))
the input name is actually "input.1", so please use that instead 
`coreml_model = convert(model_proto, image_input_names=['input.1'])`

**Comment by bhushan23** [comment]
@Umity could you please give a try to https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3 latest beta?
Feel free to re-open if you still face this issue
