### ISSUE TITLE
fatal: not a git repository: /home/onnx-coreml/build/onnx/onnx/../../.git/modules/third_party/onnx

### ISSUE THREAD

**Issue by yizhaoyanbo** [onnx/onnx-coreml#387]
I wanna to install the onnx-coreml from source to solve the "Unsupported Gather type error". When I implement this step "./install.sh", this  error occured.

**Comment by aseemw** [comment]
@smessmer do you know what could be going on?

**Comment by yizhaoyanbo** [comment]
I  install from source using this method "  pip install git+https://github.com/onnx/onnx-coreml.git  ". no problem.
