### ISSUE TITLE
UIImage and MultiArray

### ISSUE THREAD

**Issue by yizhaoyanbo** [onnx/onnx-coreml#389]
`onnx_model = onnx.load("model.onnx");
cml_model= onnx_coreml.convert(onnx_model,None, image_input_names='data');
cml_model.save("model.mlmodel");`

I wanna to use UIImage as input in coreML. So I set "image_input_names = 'data' " in the convert API. But the model's input is still multiArray. How can I deal with it?  3Q.

**Comment by aseemw** [comment]
maybe the name of the input in onnx model in not 'data'
You should use the name that is given in the onnx model, you can use Netron to visualize and find the name

**Comment by bhushan23** [comment]
@yizhaoyanbo feel free to re-open if you still need help here
