### ISSUE TITLE
Slicing is buggy when convert from Pytorch 1.0(and above)

### ISSUE THREAD

**Issue by mayokaze** [onnx/onnx-coreml#390]
As in #379 mentioned, Slicing is bugging with newest versions of Pytorch. I investigated a little bit further and found the bug comes from .onnx model. In version 1.0 Pytorch generates slicing ops for each dimension even if there is slicing on it. The code snippet from test_1d_conv 
`return result[:, :, :-self.__padding]`
fails with error
 `Traceback (most recent call last):
  File "model_test.py", line 248, in test_1d_conv
    _test_torch_model_single_io(torch_model, (1, Cin, Win), (Cin, 1, Win))  # type: ignore
  File "model_test.py", line 42, in _test_torch_model_single_io
    coreml_model = convert(onnx_model)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/converter.py", line 464, in convert
    _convert_node(builder, node, graph, err)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1851, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1345, in _convert_slice
    err.unsupported_op_configuration(builder, node, graph, 'cannot slice along batch axis')
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/onnx_coreml/_error_utils.py", line 56, in unsupported_op_configuration
    "Error while converting op of type: {}. Error message: {}\n".format(node.op_type, err_message, )
TypeError: Error while converting op of type: Slice. Error message: cannot slice along batch axis`
Is it possible to fix this by ignoring useless slicing ops?

**Comment by aseemw** [comment]
Can you try using onnx-coreml 0.4.0? 
Some of these issues should be fixed in PR #394

**Comment by MisonoMayu** [comment]
> Can you try using onnx-coreml 0.4.0?
> Some of these issues should be fixed in PR #394

Work like a charm, Thank you!

**Comment by mayokaze** [comment]
Sorry for reopening. After update to new master, I've successfully converted onnx model to mlmodel. But when I load it in an iOS project it still produces error:

`
coremlc: Error: compiler error:  Slice layer: '151': output blob channel dimension size is 0.

Input name(s) and shape(s): 
voice_input : (C,H,W) = (1, 161, 500) 
Neural Network compiler 0: 100 , name = 130, output shape : (C,H,W) = (32, 81, 250) 
Neural Network compiler 1: 130 , name = 131_scale_0_1, output shape : (C,H,W) = (32, 81, 250) 
Neural Network compiler 2: 130 , name = 131_clip_0_1, output shape : (C,H,W) = (32, 81, 250) 
Neural Network compiler 3: 130 , name = 131, output shape : (C,H,W) = (32, 81, 250) 
Neural Network compiler 4: 160 , name = 132, output shape : (C,H,W) = (32, 81, 250) 
Neural Network compiler 5: 100 , name = 135, output shape : (C,H,W) = (32, 41, 250) 
Neural Network compiler 6: 130 , name = 136_scale_0_1, output shape : (C,H,W) = (32, 41, 250) 
Neural Network compiler 7: 130 , name = 136_clip_0_1, output shape : (C,H,W) = (32, 41, 250) 
Neural Network compiler 8: 130 , name = 136, output shape : (C,H,W) = (32, 41, 250) 
Neural Network compiler 9: 160 , name = 137, output shape : (C,H,W) = (32, 41, 250) 
Neural Network compiler 10: 300 , name = 149, output shape : (C,H,W) = (1, 1312, -1) 
Neural Network compiler 11: 310 , name = 150_input_transpose0, output shape : (C,H,W) = (1312, 1, -1) 
Neural Network compiler 12: 100 , name = 150, output shape : (C,H,W) = (800, 1, -1) 
Neural Network compiler 13: 310 , name = 150_output_transpose0, output shape : (C,H,W) = (1, 800, -1) 
Neural Network compiler 14: 350 , name = 151, Command CoreMLModelCompile failed with a nonzero exit code` 
I inspected the CoreML model it still generated 3 slice ops and the first one still has with no axis attribute thus it failed to compile.

**Comment by aseemw** [comment]
We would need to look into the particular example causing this issue. Can you post a tiny code snippet that produces this issue?

**Comment by mayokaze** [comment]
> We would need to look into the particular example causing this issue. Can you post a tiny code snippet that produces this issue?

Thanks for quick reply. It's strange, I can't reproduce it in the model_test. I have checked model produced by model_test and my own, there's no difference between generated onnx model about the slicing ops but the mlmodel are different. I don't have time to investigate further. Currently I keep a 0.41 version of Pytorch to export onnx file as a workaround. I will investigate it again when I am free. Thank you.

**Comment by bhushan23** [comment]
@mayokaze could you please give a try to latest onnx-coreml beta?
https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3

**Comment by bhushan23** [comment]
feel free to re-open if you still face this issue
