### ISSUE TITLE
NotImplementedError: Unsupported ONNX ops of type: RandomNormal

### ISSUE THREAD

**Issue by jbmaxwell** [onnx/onnx-coreml#391]
I'm hitting this Unsupported ONNX ops error when trying to convert a VAE from PyTorch to ONNX to CoreML.

The only place I use `randn()` in the model is in the `reparametrize` function:

    def reparametrize(self, mu, logvar):
        std = logvar.mul(0.5).exp_()
        if self.have_cuda:
            eps = torch.randn(self.bs, self.nz, device='cuda')
        else:
            eps = torch.randn(self.bs, self.nz)
        return eps.mul(std).add_(mu)

Is there some way to add this by hand? I'm surprised that this is an issue, since generating a random normal tensor is pretty standard.

NOTE: I do recognize that, in many cases, only the decoder would be converted for a VAE, using a noise vector as input (i.e., from the host app). However, I'm using the VAE for "correcting" inputs, so to speak, so I need to input an image. I suppose it's conceivable that I could convert the encoder and decoder separately, and in my host app use the encoder to get my `mu, logvar`, then send _that_ into the decoder... but that seems like a lot of messing around...

**Comment by aseemw** [comment]
Custom layers. 

Since random data generation is n to common for inference tasks, this particular operation is not present in the CoreML spec.

**Comment by jbmaxwell** [comment]
Ugh... okay, I think I've seen a blog post on that. Will give it a go. Thanks.

**Comment by jbmaxwell** [comment]
Do you have any suggestions as to how this might be done? The ONNX `RandomNormal` custom layer is failing in Xcode because the layer has no inputs. Can I somehow add a bogus input of some kind?

**Comment by aseemw** [comment]
Yes you may need to add an input. You can add sth like mean and variance and then produce the output which are samples drawn from that distribution.

**Comment by bhushan23** [comment]
Issue resolved with suggestion of adding custom layer.
