### ISSUE TITLE
Concat not supported along batch axis

### ISSUE THREAD

**Issue by erezposner** [onnx/onnx-coreml#399]
Hi, i'm trying to perform a concatenation of 4 layers as follows:

basically input tensor is padded and cropped to 4 identical sized tensors stored at ''res'' eventually to be concatenated.

i get this error:

``` File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/onnx/lib/python2.7/site-packages/onnx_coreml/converter.py", line 468, in convert
    _convert_node(builder, node, graph, err)
  File "/anaconda3/envs/onnx/lib/python2.7/site-packages/onnx_coreml/_operators.py", line 1908, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/anaconda3/envs/onnx/lib/python2.7/site-packages/onnx_coreml/_operators.py", line 818, in _convert_concat
    return err.unsupported_op_configuration(builder, node, graph, "Concat not supported along batch axis")
  File "/anaconda3/envs/onnx/lib/python2.7/site-packages/onnx_coreml/_error_utils.py", line 56, in unsupported_op_configuration
    "Error while converting op of type: {}. Error message: {}\n".format(node.op_type, err_message, )
TypeError: Error while converting op of type: Concat. Error message: Concat not supported along batch axis
```

a python snippet to reproduce the error is attached below, thank you!

```
class multiMaxPooling(nn.Module):
    def __init__(self, kW, kH, dW, dH):
        super(multiMaxPooling, self).__init__()
        layers = []
        self.padd = []
        for i in range(0, dH):
            for j in range(0, dW):
                self.padd.append((-j, -i))
                layers.append(nn.MaxPool2d(kernel_size=(kW, kH), stride=(dW, dH)))
        self.max_layers = nn.ModuleList(layers)
        self.s = dH

    def forward(self, x):

        hh = []
        ww = []
        res = []

        for i in range(0, len(self.max_layers)):
            pad_left, pad_top = self.padd[i]
            pad_left, pad_top = abs(pad_left), abs(pad_top)
            h, w = x.size()[2], x.size()[3]
            _x = x[...,pad_top:h-pad_top,pad_left:w-pad_left]
            _x = self.max_layers[i](_x)
            h, w = _x.size()[2], _x.size()[3]
            hh.append(h)
            ww.append(w)
            res.append(_x)
        max_h, max_w = np.max(hh), np.max(ww)
        for i in range(0, len(self.max_layers)):
            _x = res[i]
            h, w = _x.size()[2], _x.size()[3]

            pad_top = np.floor((max_h - h.item()) / 2).astype(int)
            pad_bottom = np.ceil((max_h - h.item()) / 2).astype(int)
            pad_left = np.floor((max_w - w.item()) / 2).astype(int)
            pad_right = np.ceil((max_w - w.item()) / 2).astype(int)
            _x = F.pad(_x, [pad_left, pad_right, pad_top, pad_bottom], value=0)

            res[i] = _x
        return torch.cat(res, 0)
```

**Comment by aseemw** [comment]
what is the shape of `x` that you used in the function call `forward(self, x)`?

**Comment by erezposner** [comment]
input shape to ```forward(self, x)``` is `[1,8,972,1292]`.

the expected output would be `[4,8,486,646]`. this is accomplished by splitting the `x` last two dimensions into 4 at the size of `972/2=486` and `1292/2=646` stored as 4 different batches.

**Comment by aseemw** [comment]
CoreML tensors are rank 5 (internally) : [Seq, Batch, C, H, W]. Concat operation is not supported along the Batch axis. In fact its only supported along C axis, the converter internally transposes the tensors to support all other axis except batch. (transpose layer does not move the batch dimension which is sort of fixed) 

so maybe you can try reshaping the tensor to rank 5 before concat to give (4,1,8,486,646). 

Are you trying to do a max pooling operation with padding? The CoreML pool layer should be able to do that directly. See https://apple.github.io/coremltools/coremlspecification/sections/NeuralNetwork.html#poolinglayerparams, https://github.com/apple/coremltools/blob/master/docs/APIExamples.md#building-an-mlmodel-from-scratch-using-neural-network-builder

what is `F` in `F.pad` in the code snippet?

**Comment by bhushan23** [comment]
@erezposner support for concat across any axis is added with latest beta https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3

Feel free to re-open if you still face any issue for concat conversion
