### ISSUE TITLE
Metal device not found

### ISSUE THREAD

**Issue by MetaDev** [onnx/onnx-coreml#400]
when I try to convert a model:
```
model = onnx.load('../Models/SplitModel.proto')
coreml_model = convert(
    model
)
```
I get the error:
 

> Traceback (most recent call last):
>   File "/Users/Harald/Github/Liftkit/LIFTkit-models/Scripts/convert_onnx_coreml.py", line 39, in <module>
>     model
>   File "/Users/Harald/.conda/envs/py36/lib/python3.6/site-packages/onnx_coreml/converter.py", line 573, in convert
>     mlmodel = MLModel(builder.spec)
>   File "/Users/Harald/.conda/envs/py36/lib/python3.6/site-packages/coremltools/models/model.py", line 216, in __init__
>     self.__proxy__ = _get_proxy_from_spec(filename)
>   File "/Users/Harald/.conda/envs/py36/lib/python3.6/site-packages/coremltools/models/model.py", line 104, in _get_proxy_from_spec
>     return _MLModelProxy(filename)
> ValueError: Metal device not found. 
>
Any idea to what I am doing wrong?

**Comment by ElteHupkes** [comment]
So since this is basically the only result on Google for this error, I figured I'd respond - I'm getting it too, using `tfcoreml`. Haven't figured out how to fix it so far, unfortunately.

**Comment by ElteHupkes** [comment]
Ok scratch that last comment. If I create a fresh Python 3 virtualenv without conda, everything works as expected. No idea what's going on here, conda seems to like messing with me.

**Comment by bhushan23** [comment]
Issue resolved.
