### ISSUE TITLE
UnboundLocalError: local variable 'coreml_shape' referenced before assignment

### ISSUE THREAD

**Issue by yizhaoyanbo** [onnx/onnx-coreml#401]
This error occurs while converting onnx to mlmodel . The whole imformation is following:

`Traceback (most recent call last):
  File "onnx2mlmodel.py", line 8, in <module>
    cml_model= onnx_coreml.convert(onnx_model)
  File "/home/riddick/.local/lib/python3.6/site-packages/onnx_coreml/converter.py", line 464, in convert
    _convert_node(builder, node, graph, err)
  File "/home/riddick/.local/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1856, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/home/riddick/.local/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 520, in _convert_reshape
    new_shape = _get_coreml_target_shape(shape, builder, node, graph, err)
  File "/home/riddick/.local/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 111, in _get_coreml_target_shape
    return coreml_shape
UnboundLocalError: local variable 'coreml_shape' referenced before assignment`

**Comment by aseemw** [comment]
please give details/code snippet to reproduce the error.

**Comment by yizhaoyanbo** [comment]
@aseemw  My convert code is following:

####################
import sys
import onnx
import onnx_coreml

onnx_model = onnx.load("person_detector_onnx")
cml_model = onnx_coreml.convert(onnx_model)
cml_model.save("person_detector.mlmodel")
#####################

The error occurs in the following function in "_operators.py" file.

thanks very much.


![b6d81c70-2519-41be-9372-faf940d184aa](https://user-images.githubusercontent.com/26928415/53545554-ce92b400-3b64-11e9-9086-3448cefcc98f.png)

**Comment by yizhaoyanbo** [comment]
[person_detector.zip](https://github.com/onnx/onnx-coreml/files/2913658/person_detector.zip)

@aseemw  the model I used is in the .zip file.   thanks .

**Comment by jerett** [comment]
same problem, this occurs when transforming 4D tensor to 6D tensor. just like 

```
        assert(x.data.dim() == 4)
        B = x.data.size(0)
        C = x.data.size(1)
        H = x.data.size(2)
        W = x.data.size(3)
        ws, hs = self.stride, self.stride
        x = x.view(B, C, H // hs, hs, W // ws, ws).transpose(3, 4).contiguous()
```

**Comment by aseemw** [comment]
CoreML transpose and reshape layers cannot directly handle more than rank 4 tensors. 
However, patterns like "reshape--> transpose--> reshape", such that the starting and ending tensors are rank 4, can be converted to CoreML. 

@yizhaoyanbo @jerett Please check whether you get the error or not using PR #402
