### ISSUE TITLE
Unsupported ONNX ops of type: Var,Shape,Gather

### ISSUE THREAD

**Issue by alexanderhudym** [onnx/onnx-coreml#403]
I can convert my pytorch model to onnx, but when i try to convert onnx model to mlmodel i receive an error.
NotImplementedError: Unsupported ONNX ops of type: Var,Shape,Gather

if i change add_custom_layers to True i receive other error
ValueError: Missing initializer error in op of type Reshape, with input name = 94, output name = 104. Error message: CoreML only supports Reshape layer when the target shape is static and known apriori

**Comment by bhushan23** [comment]
@alexanderhudym support for Var, Shape, Gather is added
please give a try to latest beta https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3
