### ISSUE TITLE
Question about validating the converted model

### ISSUE THREAD

**Issue by lymanblue** [onnx/onnx-coreml#405]
Hi~

We trained a CNN model by PyTorch on a linux server.
We convert the model in the order of PyTorch => onnx => CoreML in linux.
The input name is set and the preprocessing args are included in conversion.

Could we validate the correctness of the converted CoreML model in linux before transferring it to Xcode? 
Or is the iterative development process necessary between linux and mac?

Thank you.

**Comment by aseemw** [comment]
Since the CoreML framework is only available on Mac, coremltools for prediction only works there. So you would not be able to check the correctness on linux.

**Comment by lymanblue** [comment]
I see. Thank you for your clarification~!
