### ISSUE TITLE
Clip without 'max' attribute

### ISSUE THREAD

**Issue by yuvdar** [onnx/onnx-coreml#407]
https://github.com/onnx/onnx-coreml/blob/0aad50ca811150e556e1f8fc0e3bb2014f20e199/onnx_coreml/_operators.py#L1618

1. When converting an onnx `clip` node, without `max` attribute - we have this line:
`max_limit = node.attrs.get('max',float(2^16-1))`
can you explain it? I would assume it should be `max_limit = node.attrs.get('max',float(2**16-1))`

2. In coremltools, there is a unary layer, that can act as clip with minimum threshold, any reason not to use it when the `max` attribute is not set? 
https://apple.github.io/coremltools/coremlspecification/sections/NeuralNetwork.html#unaryfunctionlayerparams

**Comment by aseemw** [comment]
Yeah it does seem like this translation can directly use the threshold unary function. 
If you get a chance please put up a PR, or I'll get to it at some point!

**Comment by yuvdar** [comment]
Created one!

**Comment by bhushan23** [comment]
Fixed with https://github.com/onnx/onnx-coreml/pull/408
