### ISSUE TITLE
rename feature

### ISSUE THREAD

**Issue by leonzfa** [onnx/onnx-coreml#410]
I want to change the output name of my .mlmodel.
```
import sys
import coremltools
from coremltools.models import MLModel
from coremltools.models.utils import *

spec = load_spec("my_model.mlmodel")
new_mlmodel = MLModel(spec)
coremltools.utils.rename_feature(spec, '1594', 'output')
coremltools.utils.rename_feature(spec, '0', 'image')
coremltools.utils.save_spec(spec, 'my_model_v2.mlmodel')
```
The aboved code can run properly. But when I import the my_model_v2.mlmodel in to Xcode(Swift), it raises the error: "Command CoreMLModelCompile failed with a nonzero exit code".

**Comment by aseemw** [comment]
Hmm...do you only get the error when you rename the feature? If they are not renamed, does it work correctly?

**Comment by leonzfa** [comment]
I found that there is a preprocessing (but not named layer) in the spec, which takes “0” as input. I have modified the utils.py file and it works.

**Comment by bhushan23** [comment]
@leonzfa what modification resolved the issue? You can send PR if you think it's a generic fix

**Comment by bhushan23** [comment]
closing issue due to no resolution
