### ISSUE TITLE
Concat problem while converting

### ISSUE THREAD

**Issue by xfarxod** [onnx/onnx-coreml#411]
I get this error while converting model to core-ml:

```
 "Error while converting op of type: {}. Error message: {}\n".format(node.op_type, err_message, )
TypeError: Error while converting op of type: Concat. Error message: unable to translate constant array shape to CoreML shape"
```

Pytorch tensor shape is:
```
A is (1, 128, 128, 256)
B is (1, 1, 128, 256)
```

`C = torch.cat((A,B),1)`

Expected C value is (1, 129, 128, 256)

I tried reshape tensors to: 
```
A = (1, 1, 128, 128, 256)
B = (1, 1, 1, 128, 256)
```

But still have 
unable to translate constant array shape to CoreML shape Error.

**Comment by bhushan23** [comment]
@xfarxod can you try with latest beta coremltools 3.0b2?

Following works without any error with latest beta
```
import torch

class cat_model(torch.nn.Module):
    def __init__(self):
        super(cat_model, self).__init__()

    def forward(self, a, b):
        c = torch.cat((a, b), 1)
        # print(c.shape)
        return c

a = torch.randn((1, 128, 128, 256))
b = torch.randn((1, 1, 128, 256))

model = cat_model()
torch.onnx.export(model, (a, b), 'cat_model.onnx')

import onnx
model = onnx.load('cat_model.onnx')
onnx.checker.check_model(model)
print(onnx.helper.printable_graph(model.graph))

from onnx_coreml import convert
mlmodel = convert(model)
```

> 
> Using TensorFlow backend.
> 1/1: Converting Node Type Concat
> Translation to CoreML spec completed. Now compiling the CoreML model.
> Model Compilation done.

**Comment by bhushan23** [comment]
Closing as issue no longer exists

**Comment by xfarxod** [comment]
Thank you for your response and sorry for my late reply.
Works for me!!!
