### ISSUE TITLE
why not coreml reduce operator support Batch dim?

### ISSUE THREAD

**Issue by noyami2033** [onnx/onnx-coreml#413]
https://github.com/onnx/onnx-coreml/blob/cd4e491a61daeb9f1d56d3e277ed3d06c40bd7ad/onnx_coreml/_operators.py#L964
Thank you for coreml. 
I would like to use a  reduce mean operator in dim 0 which is batch dim. But in the code above that, it seems like batch dim is not supported. 
the error message is 
`TypeError: Error while converting op of type: ReduceMean. Error message: Unable to translate axes attribute to CoreML axis parameter for [0]`
So could you help me to deal with this problem? I can change the source by myself. Thank you!

**Comment by bhushan23** [comment]
@noyami2033 could you please give a try to latest beta?
we have added support for reduce operation across all the axis https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3

**Comment by bhushan23** [comment]
@noyami2033 closing as support for reduce mean is added
Feel free to re-open if you need more help here
