### ISSUE TITLE
input image problem with pytorch model to coremlmodel

### ISSUE THREAD

**Issue by lgyStoic** [onnx/onnx-coreml#414]
I have a pytorch model  with input 3 * 1000 * 1000(CHW), output 3 * 2000 * 2000 as super resolution, then convert to coreml model,  Then I write a checker for pytorch model,  the result is correct. Because I use torchvision do image preprocess, so I store processed data in .npy file .  Use that .npy file, and I am confirm the result in coreml model.

`But` when I use onnx-coreml convert function,  like this
`coreml_model = convert(model_proto, image_input_names=['lr_image'], image_output_names=['sr_image'], preprocessing_args={'image_scale':1/255.0}, deprocessing_args={'image_scale':255.0})
`
then I input a PIL image (HWC) for coremltools , and  coremltools always print `ValueError: axes don't match array` how to solve that problem......

Even that, I drag that model to Xcode, using vision framework, it works, but got incorrect image..

**Comment by lgyStoic** [comment]
Input name(s) and shape(s):
lr_image : (C,H,W) = (3, 1000, 1000)
Neural Network compiler 0: 100 , name = 59, output shape : (C,H,W) = (3, 1000, 1000)
Neural Network compiler 1: 100 , name = 60, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 2: 100 , name = 61, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 3: 130 , name = 62, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 4: 100 , name = 63, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 5: 130 , name = 64, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 6: 100 , name = 65, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 7: 230 , name = 66, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 8: 130 , name = 67, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 9: 320 , name = 68, output shape : (C,H,W) = (128, 1000, 1000)
Neural Network compiler 10: 100 , name = 69, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 11: 130 , name = 70, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 12: 100 , name = 71, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 13: 130 , name = 72, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 14: 100 , name = 73, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 15: 130 , name = 74, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 16: 100 , name = 75, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 17: 230 , name = 76, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 18: 130 , name = 77, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 19: 320 , name = 78, output shape : (C,H,W) = (192, 1000, 1000)
Neural Network compiler 20: 100 , name = 79, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 21: 130 , name = 80, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 22: 100 , name = 81, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 23: 130 , name = 82, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 24: 100 , name = 83, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 25: 130 , name = 84, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 26: 100 , name = 85, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 27: 230 , name = 86, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 28: 130 , name = 87, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 29: 320 , name = 88, output shape : (C,H,W) = (256, 1000, 1000)
Neural Network compiler 30: 100 , name = 89, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 31: 130 , name = 90, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 32: 320 , name = 91, output shape : (C,H,W) = (128, 1000, 1000)
Neural Network compiler 33: 100 , name = 92, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 34: 130 , name = 93, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 35: 100 , name = 94, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 36: 130 , name = 95, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 37: 100 , name = 96, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 38: 130 , name = 97, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 39: 100 , name = 98, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 40: 230 , name = 99, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 41: 130 , name = 100, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 42: 320 , name = 101, output shape : (C,H,W) = (128, 1000, 1000)
Neural Network compiler 43: 100 , name = 102, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 44: 130 , name = 103, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 45: 100 , name = 104, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 46: 130 , name = 105, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 47: 100 , name = 106, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 48: 130 , name = 107, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 49: 100 , name = 108, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 50: 230 , name = 109, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 51: 130 , name = 110, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 52: 320 , name = 111, output shape : (C,H,W) = (192, 1000, 1000)
Neural Network compiler 53: 100 , name = 112, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 54: 130 , name = 113, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 55: 100 , name = 114, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 56: 130 , name = 115, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 57: 100 , name = 116, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 58: 130 , name = 117, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 59: 100 , name = 118, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 60: 230 , name = 119, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 61: 130 , name = 120, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 62: 320 , name = 121, output shape : (C,H,W) = (256, 1000, 1000)
Neural Network compiler 63: 100 , name = 122, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 64: 130 , name = 123, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 65: 320 , name = 124, output shape : (C,H,W) = (192, 1000, 1000)
Neural Network compiler 66: 100 , name = 125, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 67: 130 , name = 126, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 68: 100 , name = 127, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 69: 130 , name = 128, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 70: 100 , name = 129, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 71: 130 , name = 130, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 72: 100 , name = 131, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 73: 230 , name = 132, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 74: 130 , name = 133, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 75: 320 , name = 134, output shape : (C,H,W) = (128, 1000, 1000)
Neural Network compiler 76: 100 , name = 135, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 77: 130 , name = 136, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 78: 100 , name = 137, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 79: 130 , name = 138, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 80: 100 , name = 139, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 81: 130 , name = 140, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 82: 100 , name = 141, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 83: 230 , name = 142, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 84: 130 , name = 143, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 85: 320 , name = 144, output shape : (C,H,W) = (192, 1000, 1000)
Neural Network compiler 86: 100 , name = 145, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 87: 130 , name = 146, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 88: 100 , name = 147, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 89: 130 , name = 148, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 90: 100 , name = 149, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 91: 130 , name = 150, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 92: 100 , name = 151, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 93: 230 , name = 152, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 94: 130 , name = 153, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 95: 320 , name = 154, output shape : (C,H,W) = (256, 1000, 1000)
Neural Network compiler 96: 100 , name = 155, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 97: 130 , name = 156, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 98: 320 , name = 157, output shape : (C,H,W) = (256, 1000, 1000)
Neural Network compiler 99: 100 , name = 158, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 100: 130 , name = 159, output shape : (C,H,W) = (64, 1000, 1000)
Neural Network compiler 101: 100 , name = 160, output shape : (C,H,W) = (256, 1000, 1000)
Neural Network compiler 102: 130 , name = 161, output shape : (C,H,W) = (256, 1000, 1000)
Neural Network compiler 103: 300 , name = 163, output shape : (C,H,W) = (2, 64, 1000000)
Neural Network compiler 104: 310 , name = 164, output shape : (C,H,W) = (1000000, 2, 64)
Neural Network compiler 105: 300 , name = pixel_shuffle_reshape, output shape : (C,H,W) = (1000, 2, 64)
Neural Network compiler 106: 310 , name = pixel_shuffle_transpose, output shape : (C,H,W) = (2, 1000, 64)
Neural Network compiler 107: 300 , name = 166, output shape : (C,H,W) = (64, 2000, 2000)
Neural Network compiler 108: 100 , name = 167, output shape : (C,H,W) = (3, 2000, 2000)
Neural Network compiler 109: 100 , name = sr_image, output shape : (C,H,W) = (3, 2000, 2000)
Neural Network compiler 110: 245 , name = sr_image_0, output shape : (C,H,W) = (3, 2000, 2000)

**Comment by bhushan23** [comment]
can you share your model?

**Comment by bhushan23** [comment]
@lgyStoic can you provide model and image?

**Comment by bhushan23** [comment]
@lgyStoic closing for now.
Feel free to re-open with model
