### ISSUE TITLE
NotImplementedError: Unsupported ONNX ops of type: ConstantOfShape

### ISSUE THREAD

**Issue by nitsanp** [onnx/onnx-coreml#415]
Hi

I'm trying to export onnx to core ml and I'm getting the following error:

`---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-36-b188608f0d78> in <module>()
----> 1 mlmodel = onnx_coreml.convert(model_onnx)
      2 # mlmodel.save('models/pytorch_lstm12_1000_300619.mlmodel')

~/anaconda3/envs/tf_p36/lib/python3.6/site-packages/onnx_coreml/converter.py in convert(model, mode, image_input_names, preprocessing_args, image_output_names, deprocessing_args, class_labels, predicted_feature_name, add_custom_layers, custom_conversion_functions, onnx_coreml_input_shape_map)
    457     '''
    458     if not add_custom_layers:
--> 459         _check_unsupported_ops(graph.nodes)
    460 
    461     err = ErrorHandling(add_custom_layers,

~/anaconda3/envs/tf_p36/lib/python3.6/site-packages/onnx_coreml/converter.py in _check_unsupported_ops(nodes)
    143     if len(unsupported_op_types) > 0:
    144         raise NotImplementedError("Unsupported ONNX ops of type: %s" % (
--> 145             ','.join(unsupported_op_types)))
    146 
    147 

NotImplementedError: Unsupported ONNX ops of type: ConstantOfShape`

**Comment by bhushan23** [comment]
I will be sending PR this week

**Comment by nitsanp** [comment]
OK, waiting.

**Comment by bhushan23** [comment]
@nitsanp ConstantOfShape support has been added with https://github.com/onnx/onnx-coreml/pull/424
Could you please give a try?

**Comment by bhushan23** [comment]
@nitsanp ConstantOfShape and LSTM is now supported in CoreML 3
Note that, you will need to use Mac OS 10.15 beta
please use `disable_coreml_rank5_mapping=True` flag while converting to enable nd-tensor conversion path

**Comment by dnnagy** [comment]
I had a similar issue with `ConstantOfShape`, `LSTM`, `Gather`, and setting `add_custom_layers` to true solved it for me. I have not tested the converted model yet, but at least it converts without error message.

**Comment by nitsanp** [comment]
Thank you @dnnagy, when I set `add_custom_layers=True` I don't get that error anymore, but I still get an error when it arrives to the LSTM layer: 
`ValueError: array split does not result in an equal division`

**Comment by nitsanp** [comment]
@bhushan23 I don't understand where to find this flag

**Comment by nitsanp** [comment]
@bhushan23 I don't understand where to change this flag.

**Comment by dnnagy** [comment]
@nitsanp I can convert my model to `.mlmodel` format, but when I try to integrate it in my app, i get an error in Xcode:
<img width="696" alt="Screenshot 2019-08-06 at 11 44 58" src="https://user-images.githubusercontent.com/12029086/62529875-cc353400-b83f-11e9-94f6-78da4e610d94.png">
I think, we cannot use LSTMs currently, because it was introduced in CoreML 3, and is currently available only in Xcode 11 beta and macOS Catalina beta versions.

**Comment by nitsanp** [comment]
Thank you, I hope it will be available soon.

**Comment by bhushan23** [comment]
> @bhushan23 I don't understand where to change this flag.

@nitsanp you can pass `disable_coreml_rank5_mapping=True` to convert method here https://github.com/onnx/onnx-coreml/blob/master/onnx_coreml/converter.py#L337

This option disables rank5 mapping and allows usage of ops with nd tensor support i.e. newly introduced layers in CoreML

I see, it's not mentioned in README. Will make a change to specify what this option does.

**Comment by nitsanp** [comment]
@bhushan23 
OMG it worked!!!!! thank you so much!!!!!

**Comment by bhushan23** [comment]
closing as support for ConstantOfShape is added

**Comment by edjust** [comment]
I am having the same issue in https://github.com/onnx/tutorials/issues/150
Could someone help me that? I already pass disable_coreml_rank5_mapping=True but the error persist.

**Comment by bhushan23** [comment]
@edjust please use latest onnx-coreml beta https://github.com/onnx/onnx-coreml/#new-beta-onnx-coreml-converter-with-core-ml-3
pass `target_ios='13'` 
these ops are supported with `target_ios='13'`
