### ISSUE TITLE
NotImplementedError: Unsupported ONNX ops of type: Gather

### ISSUE THREAD

**Issue by edis219** [onnx/onnx-coreml#450]
When converting one .onnx model to CoreML, encounter this issue:
"NotImplementedError: Unsupported ONNX ops of type: Gather"

Is there any work around for it? Or any suggestions on this?

**Comment by iiSeymour** [comment]
Gather is supported with CoreML 3, you need to convert with `disable_coreml_rank5_mapping=True`.

> If True, then it disables the "RANK5_ARRAY_MAPPING" or enables the "EXACT_ARRAY_MAPPING" option in CoreML. Thus, no longer, onnx tensors are forced to map to rank 5 CoreML tensors. With this flag on, a rank r ONNX tensor, (1<=r<=5), will map to a rank r tensor in CoreML as well. This flag must be on to utilize any of the new layers added in CoreML 3 (i.e. specification version 4, iOS13)

**Comment by edis219** [comment]
Thanks a lot Chris! The Gather ops are supported in CoreML 3

> Gather is supported with CoreML 3, you need to convert with `disable_coreml_rank5_mapping=True`.
> 
> > If True, then it disables the "RANK5_ARRAY_MAPPING" or enables the "EXACT_ARRAY_MAPPING" option in CoreML. Thus, no longer, onnx tensors are forced to map to rank 5 CoreML tensors. With this flag on, a rank r ONNX tensor, (1<=r<=5), will map to a rank r tensor in CoreML as well. This flag must be on to utilize any of the new layers added in CoreML 3 (i.e. specification version 4, iOS13)
