### ISSUE TITLE
cannot add op after concat

### ISSUE THREAD

**Issue by beibei1998** [onnx/onnx-coreml#453]
hi 
when I convert ONNX model to CoreML model, I met a problem that I cannot add any op after concat. When I try to add op such as conv or max pool, it would have the error:TypeError: Error while converting op of type: MaxPool. Error message: Input shape not available 

this is my error info:
![image](https://user-images.githubusercontent.com/43979867/63510638-9ff10700-c511-11e9-9b9c-cc93ce54e201.png)

**Comment by bhushan23** [comment]
@beibei1998 which ONNX version are you using? ONNX shape inference had few bugs which does not compute input shape which is required for above ops.
If ONNX 1.5.0 also does not work for you. I would recommend to build it from source from tot and try.
I recently faced similar issue, tot ONNX worked for me

**Comment by beibei1998** [comment]
I used the latest version of onnx which is 1.5.0. but it seems not work. and my onnx－coreml is also 3.0beta.

**Comment by bhushan23** [comment]
@beibei1998 is it possible to share ONNX model? also, please try with latest ONNX built from source. As I mentioned it worked for me in past.

**Comment by beibei1998** [comment]
thx. but i just do the convert work. what i want to ask now is that i have checked the output of the concat and the input of conv and they matches, both of them are （1,1,3,512,512）why the input is not
 available?

**Comment by beibei1998** [comment]
i will try to build source thx very much

**Comment by beibei1998** [comment]
I have rebuilt the onnx and onnx-coreml source, it seems not work. The error still exists.

**Comment by bhushan23** [comment]
@beibei1998 is it possible for you to share ONNX model? Looks like something is off with onnx shape inference

**Comment by beibei1998** [comment]
I will share the model later. may I ask now why it is incorrect when conv is after concat while other convs have no error

**Comment by bhushan23** [comment]
there is a possibility that ONNX graph is not able to compute shape for concat op (possible bug) and hence, shape is not provided to conv layer

**Comment by beibei1998** [comment]
this is my model code, the error exists between the concat and conv


[simple_seg.txt](https://github.com/onnx/onnx-coreml/files/3533176/simple_seg.txt)

**Comment by beibei1998** [comment]
can this bug fix？

**Comment by beibei1998** [comment]
![image](https://user-images.githubusercontent.com/43979867/63737577-78a38c80-c8b9-11e9-8693-e7f94a60617e.png)

convert script:

import torch
import torch.onnx as torch_onnx
from torch.autograd import Variable
from networks.versa_v2 import versa_v2, SegMattingNet
model = versa_v2()
model.load_state_dict(torch.load(path_model_path))
input_shape = (3, 512, 512)
input_names = ["input_array"]
output_names = ["output_array"]
dummy_input = Variable(torch.randn(1, *input_shape))
output = torch_onnx.export(model,
                          dummy_input,
                          model_onnx_path,
                          verbose=False,
                          input_names=input_names,
                          output_names=output_names)

**Comment by beibei1998** [comment]
may I ask that if this is the bug of onnx-coreml or my script/model?

**Comment by beibei1998** [comment]
thank you very much!
upcoming coremltools beta release?do you mean 1.0b2?

**Comment by beibei1998** [comment]
ok i get
thank u  very much
wait for the latest version!

**Comment by bhushan23** [comment]
@beibei1998 could you please install onnx latest version from source? Read here for instructions https://github.com/onnx/onnx#source

Shape inference is fixed in changes later than 1.5.0 release and you should be able to convert with it.

**Comment by beibei1998** [comment]
thank u
I have reinstalled ONNX from source today, but it seems no difference
if I need to update others?

**Comment by bhushan23** [comment]
@beibei1998 could you please try with latest beta? SoftMax and Rank information change is available in 1.0b3

**Comment by bhushan23** [comment]
have created PyTorch issue for the same https://github.com/pytorch/pytorch/issues/27376

**Comment by AnasArram** [comment]
> @beibei1998 thanks for providing more information
> This is blocked on due to [onnx/onnx#1420](https://github.com/onnx/onnx/issues/1420)
> We have a solution via coremltools and it will be available in upcoming coremltools beta release.
> 
> vesa_simple is able to convert with the expected rank change.
> There are few issues i would like to point to you
> 
> 1. PyTorch is export ONNX op v9 and we not support v10
> 2. Shape inference issue is hitting for conv and batchnorm and hence blocked on above change
> 
> I am using following conversion script to force upsample scalar factor=2 (which is known) and using slice operator for v9
> 
> ```
> import onnx
> from onnx_coreml import convert
> from coremltools.proto import NeuralNetwork_pb2
> 
> INT_MAX = 2**30
> def _convert_upsample(builder, node, graph, err):
>     params = NeuralNetwork_pb2.CustomLayerParams()
>     params.className = node.op_type
>     params.description = "Custom layer that corresponds to the ONNX op {}".format(node.op_type)
> 
>     if 'scales' in node.attrs:
>         scales = node.attrs['scales']
>     elif len(node.input_tensors):
>         scales = node.input_tensors[node.inputs[1]]
>     else:
>         # HACK: Manual scales
>         scales = [1, 1, 2 * graph.shape_dict[node.inputs[0]][2],  2 * graph.shape_dict[node.inputs[0]][3]]
> 
>     scale_h = scales[2]
>     scale_w = scales[3]
>     input_shape = graph.shape_dict[node.inputs[0]]
>     target_height = int(input_shape[-2] * scale_h)
>     target_width = int(input_shape[-1] * scale_w)
> 
>     builder.add_resize_bilinear(
>         name=node.name,
>         input_name=node.inputs[0],
>         output_name=node.outputs[0],
>         target_height=target_height,
>         target_width=target_width,
>         mode='UPSAMPLE_MODE'
>     )
> 
> def _convert_slice_v9(builder, node, graph, err):
>     '''
>     convert to CoreML Slice Static Layer:
>     https://github.com/apple/coremltools/blob/655b3be5cc0d42c3c4fa49f0f0e4a93a26b3e492/mlmodel/format/NeuralNetwork.proto#L5082
>     ''' 
>     data_shape = graph.shape_dict[node.inputs[0]]
>     len_of_data = len(data_shape)
>     begin_masks = [True] * len_of_data
>     end_masks = [True] * len_of_data
> 
>     default_axes = list(range(len_of_data))
>     default_steps = [1] * len_of_data
>     
>     ip_starts = node.attrs.get('starts')
>     ip_ends = node.attrs.get('ends')
>     axes = node.attrs.get('axes', default_axes)
>     steps = node.attrs.get('steps', default_steps)
> 
>     starts = [0] * len_of_data
>     ends = [0] * len_of_data
> 
>     for i in range(len(axes)):
>         current_axes = axes[i]
>         starts[current_axes] = ip_starts[i]
>         ends[current_axes] = ip_ends[i]
>         if ends[current_axes] != INT_MAX or ends[current_axes] < data_shape[current_axes]:
>             end_masks[current_axes] = False
> 
>         if starts[current_axes] != 0:
>             begin_masks[current_axes] = False
> 
>     builder.add_slice_static(
>         name=node.name,
>         input_name=node.inputs[0],
>         output_name=node.outputs[0],
>         begin_ids=starts,
>         end_ids=ends,
>         strides=steps,
>         begin_masks=begin_masks,
>         end_masks=end_masks
>     )
> 
> ## Load ONNX Model
> model = onnx.load('/Volumes/Common/Work/issues/github/concat-shape/simple_seg.onnx')
> 
> ## Convert ONNX Model into CoreML MLModel
> c_model = convert(model, disable_coreml_rank5_mapping=True, custom_conversion_functions={'Upsample':_convert_upsample, "Slice": _convert_slice_v9})
> ```

i got the following error when i run the project in xcode: 

coremlc: Error: compiler error:  Espresso exception: "Invalid blob shape": generic_elementwise_kernel: cannot broadcast [48, 64, 32, 1, 1] and [96, 128, 32, 1, 1]

this is from upsampling, the second list is the scales that passed to 'builder.add_resize_bilinear'.
the two lists are in opposite order. looks they should be like: [1, 1, 32, 64, 48] and [1, 1, 32, 128, 96].
Any idea about this?

**Comment by colinheye** [comment]
I tried to use the conversion script to solve the upsample scale issue, but I receive an error saying that disable_coreml_rank5_mapping is not a recognized argument for convert. Do I need to use a beta version? I am using onnx-coreml version 1.2 and coremltools version 3.3

**Comment by rdv0011** [comment]
Hello.
  I have tried to use the above mentioned script, but it seems graph.shape_dict does not contain needed indices:
```bash
Exception has occurred: KeyError
'356'
  File "/Users/dmitryrybakov/Documents/hand-tracking/hand-pose-estimation/3D-Hand-Pose-Estimation/convert2CoreML.py", line 28, in _convert_upsample
    scales = [1, 1, 2 * graph.shape_dict[node.inputs[0]][2],  2 * graph.shape_dict[node.inputs[0]][3]]
```

I am using CoreML tools ver. 3.3:
```
Requirement already up-to-date: coremltools in /Users/dmitryrybakov/miniconda3/envs/pt/lib/python3.5/site-packages (3.3)
```

**Comment by bhushan23** [comment]
> disable_coreml_rank5_mapping

@colinheye you should use `minimum_ios_deployment_target` option instead of `disable_coreml_rank5_mapping`
ref: https://github.com/onnx/onnx-coreml#parameters

**Comment by bhushan23** [comment]
@rdv0011 above example is for reference purpose. If you know the input shape for Upsample, you can provide that in custom conversion function.

We don't know input shape because, onnx shape inference is not able to infer shape beyond cat or similar layers. But in practice, you should know shape and can provide it.

I would recommend to provide this hard shape

**Comment by rdv0011** [comment]
@bhushan23 
Thanks for giving an instruction how to fix it it worked for me. I have another question regarding a Tile block. It seems it expects an input to be presented in the input_tensor which is not the case for me. Do you know what to pass a values for an ```reps``` argument in the function ```builder.add_tile()```?
![Screenshot 2020-04-18 at 22 15 42](https://user-images.githubusercontent.com/4025952/79670383-c3fd0900-81c2-11ea-9fcc-a33af29bb4e9.png)

**Comment by colinheye** [comment]
> > disable_coreml_rank5_mapping
> 
> @colinheye you should use `minimum_ios_deployment_target` option instead of `disable_coreml_rank5_mapping`
> ref: https://github.com/onnx/onnx-coreml#parameters

Thank you, this appears to fix that issue, but now I receive a KeyError 
```
File "onnx_coreml3.py", line 39, in _convert_slice_v9
    data_shape = graph.shape_dict[node.inputs[0]]
KeyError: '88' 
```

**Comment by bhushan23** [comment]
> @bhushan23
> Thanks for giving an instruction how to fix it it worked for me. I have another question regarding a Tile block. It seems it expects an input to be presented in the input_tensor which is not the case for me. Do you know what to pass a values for an `reps` argument in the function `builder.add_tile()`?
> ![Screenshot 2020-04-18 at 22 15 42](https://user-images.githubusercontent.com/4025952/79670383-c3fd0900-81c2-11ea-9fcc-a33af29bb4e9.png)

You should the number of times to replicate compile time and hence it should be part of input tensors. 
Ref:
Here is proto documentation: https://github.com/apple/coremltools/blob/master/mlmodel/format/NeuralNetwork.proto#L5418
Here is builder API:  https://github.com/apple/coremltools/blob/master/coremltools/models/neural_network/builder.py#L4298

**Comment by bhushan23** [comment]
> > > disable_coreml_rank5_mapping
> > 
> > 
> > @colinheye you should use `minimum_ios_deployment_target` option instead of `disable_coreml_rank5_mapping`
> > ref: https://github.com/onnx/onnx-coreml#parameters
> 
> Thank you @bhushan23 , this appears to fix that issue, but now I receive a KeyError. Any ideas?
> 
> ```
> File "onnx_coreml3.py", line 39, in _convert_slice_v9
>     data_shape = graph.shape_dict[node.inputs[0]]
> KeyError: '88' 
> ```

@colinheye please refer to this comment https://github.com/onnx/onnx-coreml/issues/453#issuecomment-615485972

I posted this as an example and you can manually fix the input shape if you know it (highly recommend to encode shape you are expecting)

**Comment by bhushan23** [comment]
Closing out this issue as does have work around with custom conversion functions and will be unblocked partially after upgrading to new onnx version (hopefully with new shape inference fixes)
Please feel free to re-open or comment if you need more help on this.
