### ISSUE TITLE
KeyError during Converting Node Type Slice

### ISSUE THREAD

**Issue by yehorchankov** [onnx/onnx-coreml#458]
### Description 
I was trying to convert pytorch model to CoreML model. To do this I export my pytorch model as ONNX using `torch.onnx.export` method. Later I use `onnx_coreml.convert` method to convert the model to CoreML representation. 

### Code
Unfortunately, I cannot share full pytorch model here. The code to convert model is as simple as:
```
my_model = MyModel()
torch.onnx.export(my_model, net_input, 'my_model.onnx', inputs, outputs)
onnx_model = onnx.load('my_model.onnx')
onnx.checker.check_model(onnx_model)
coreml_model = convert(
        onnx_model,
        disable_coreml_rank5_mapping=True
)
coreml_model.save('my_model.mlmodel')
```
### Error
But it gives me the next output:
```
1/155: Converting Node Type Conv
.... skip part of console output ....
131/155: Converting Node Type Slice
Traceback (most recent call last):
  File "/snap/pycharm-professional/151/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/snap/pycharm-professional/151/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-professional/151/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/snap/pycharm-professional/151/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/151/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "~/torch2onnx.py", line 115, in <module>
    main()
  File "~/torch2onnx.py", line 55, in main
    export_utils.onnx2coreml(onnx_model, 'fb_sl.mlmodel')
  File "~/model_utils/export_utils.py", line 10, in onnx2coreml
    disable_coreml_rank5_mapping=True
  File "~/envs/p37/lib/python3.7/site-packages/onnx_coreml/converter.py", line 573, in convert
    _convert_node_nd(builder, node, graph, err)
  File "~/envs/p37/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 1992, in _convert_node_nd
    return converter_fn(builder, node, graph, err)
  File "~/envs/p37/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 1649, in _convert_slice
    if node.inputs[1] in node.input_tensors and node.inputs[2] in node.input_tensors:
IndexError: list index out of range
```

### Environment
My environment is:
* python 3.7.3
* pytorch 1.2.0
* onnx 1.5.0
* coremltools 3.0b5
* onnx-coreml 1.0b2

 ### Fixes
I have tracked the error and fixed it by reverting the code of `_operators_nd.py` module to the state when the `Slice` operation had been introduced by `_convert_slice` method. See this [diff](https://github.com/onnx/onnx-coreml/commit/ac69fcea7f79822744ee49f8fc5c9a07edc5f31c#diff-137e66609eeaaa6436cb2a01692a3922R230). The code was updated few days ago by #452 (Moving to ONNX version 1.5.0). 

### Question
So the question is why don't my code work as expected with the latest version of ONNX and onnx-coreml?

**Comment by yehorchankov** [comment]
@bhushan23 thank you for advice! Currently this solution works for me.

But how can I convert my model to operator version 10? As I mentioned, my onnx is of version 1.5.0, but the model is still operator version 9.

**Comment by bhushan23** [comment]
@yehorchankov pytorch export is generating version 9 model (also ONNX 1.4.0 and not 1.5.0)
I have asked this question on discuss forum here https://discuss.pytorch.org/t/exporting-onnx-v5-from-torch-onnx-export/54158 as pytorch release states to support version 10

Meanwhile, tried converting through ONNX version converter but seems like slice is not yet added in there. https://github.com/onnx/onnx/blob/master/onnx/version_converter.py

**Comment by marcoleewow** [comment]
@bhushan23 thanks for your custom function code. May I ask what is `INT_MAX` in your code?

**Comment by marcoleewow** [comment]
I used `INT_MAX = 2 ** 30` from the source, I think it's correct.

However, when I try to do inference on the CoreML model I keep getting `exception: "Invalid blob shape"`, I guess flexible shape with LSTM CoreML model still doesn't work atm?

**Comment by bhushan23** [comment]
@marcoleewow can you open new issue and attach ONNX model?

**Comment by marcoleewow** [comment]
Guys after battling with ONNX and CoreML for the whole day, I finally solved the issue! The main catch is: 
1. we must use Mac OS Catalina 
2. `nn.LSTM(..., batch_first=True)`

You guys can follow the code from here, I added flexible shape as well:
https://gist.github.com/marcoleewow/26a0d5e23e35528262556697c62c2a50
