### ISSUE TITLE
When, A,B,C are all in the input_tensors of "Gemm" node, the "_convert_gemm" still make A as the input_names

### ISSUE THREAD

**Issue by edis219** [onnx/onnx-coreml#461]
When, A,B,C are all in the input_tensors of "Gemm" node, the "_convert_gemm" still make A as the input_names. Then "Error reading protobuf spec. validator error: Layer '110' consumes an input named '106' which is not present in this network."

The model spec:
def model(image_gray, edge, mask) :
        90 =  loadConstantND (shape = (1,),  value = [1.0] )
        91 =  subtractBroadcastable (90, mask)
        92 =  multiplyBroadcastable (edge, 91)
        93 =  loadConstantND (shape = (1,),  value = [1.0] )
        94 =  subtractBroadcastable (93, mask)
        95 =  multiplyBroadcastable (image_gray, 94)
        96 =  addBroadcastable (95, mask)
        97 =  concatND (96, 92, mask)
        98 =  padding (97)
        110 =  batchedMatmul (106)
...

**Comment by bhushan23** [comment]
@edis219 could you please share a snippet of ONNX model for repro?

**Comment by edis219** [comment]
> @edis219 could you please share a snippet of ONNX model for repro?

Hi @bhushan23 ,

I added the following code to the "_convert_gemm", this issue solved.

def _convert_gemm(builder, node, graph, err):
    '''
    convert to CoreML Tranpose (Optional) and Inner Product Layer:
    https://github.com/apple/coremltools/blob/655b3be5cc0d42c3c4fa49f0f0e4a93a26b3e492/mlmodel/format/NeuralNetwork.proto#L4180
    '''
    # Read attributes
    alpha = node.attrs.get('alpha', 1.0)
    beta = node.attrs.get('beta', 1.0)
    transA = node.attrs.get('transA', False)
    transB = node.attrs.get('transB', False)

    A = node.inputs[0]
    if A in node.input_tensors:
        A_tensor = node.input_tensors[A]
        builder.add_load_constant_nd(
            name=node.name + "_const_" + A,
            output_name='const_' + A,
            constant_value=A_tensor,
            shape=A_tensor.shape
        )
        A = 'const_'+A

**Comment by bhushan23** [comment]
@edis219 you are right
input is constant and gemm requires it to be input.
simpler way to handle this is to 
call load_input_constants method in the beginning similar to https://github.com/onnx/onnx-coreml/blob/fd6059cfd9706b0fc583da508ac2db26a808c278/onnx_coreml/_operators_nd.py#L189
```
load_input_constants(builder, node, graph, err)
```
Feel free to send a PR

**Comment by bhushan23** [comment]
closed with #472
