### ISSUE TITLE
Bilinear upsampling mapping missing

### ISSUE THREAD

**Issue by sakishinoda** [onnx/onnx-coreml#463]
Pretty sure that there is a bug in the [upsample conversion](https://github.com/onnx/onnx-coreml/blob/4d8b1cc348e2d6a983a6d38bb6921b6b77b47e76/onnx_coreml/_operators.py#L1632), where the "bilinear" node type doesn't map to "BILINEAR". I am not sure if the "linear": "BILINEAR" mapping is needed elsewhere, but this map should include "bilinear": "BILINEAR" for correct conversion.

**Comment by bhushan23** [comment]
@sakishinoda Upsample is deprecated in ONNX operator version 10
as per version-9, https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Upsample-9
I have seen ONNX version 9 models with 'linear' mode.
Do you have any ONNX model example for the same?

**Comment by sakishinoda** [comment]
Okay, this may be because I'm using pytorch version 0.4.1 to export to ONNX in the first place. Thank you
