### ISSUE TITLE
IndexError when converting LSTM network from Matlab

### ISSUE THREAD

**Issue by JT-101** [onnx/onnx-coreml#473]
I'm using the latest version from commit c36bfef, which fixed my issue in #445 . Now I get the following error (same ONNX file from Matlab as #445 )

1/8: Converting Node Type LSTM
Warning: Unsupported Feature in op of type LSTM, with input name = sequenceinput, output name = . Warning message: Forward and backward pass will use same activations. 

2/8: Converting Node Type Transpose
3/8: Converting Node Type Reshape
4/8: Converting Node Type Unsqueeze
5/8: Converting Node Type MatMul
6/8: Converting Node Type Add
7/8: Converting Node Type Flatten
8/8: Converting Node Type Softmax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/onnx_coreml/converter.py", line 568, in convert
    _convert_node_nd(builder, node, graph, err)
  File "/Library/Python/2.7/site-packages/onnx_coreml/_operators_nd.py", line 2050, in _convert_node_nd
    return converter_fn(builder, node, graph, err)
  File "/Library/Python/2.7/site-packages/onnx_coreml/_operators_nd.py", line 1811, in _convert_softmax
    add_softmax(node.outputs[0], rank=rank, axis=axis)
  File "/Library/Python/2.7/site-packages/onnx_coreml/_operators_nd.py", line 1760, in add_softmax
    transpose_axes[-3], transpose_axes[axis] = transpose_axes[axis], transpose_axes[-3]
IndexError: list index out of range

**Comment by bhushan23** [comment]
@JT-101 this should be fixed with latest coremltools (from source) and onnx-coreml

**Comment by bhushan23** [comment]
@JT-101 you might have to wait for latest coremltools version (3.1) as rank change goes into coremltools
but, meanwhile, you can use `custom_conversion_function` to use `softmax_nd`
```
def _convert_softmax(builder, node, graph, err):
    '''
    convert to CoreML SoftMax ND Layer:
    https://github.com/apple/coremltools/blob/655b3be5cc0d42c3c4fa49f0f0e4a93a26b3e492/mlmodel/format/NeuralNetwork.proto#3547
    '''
    axis = node.attrs.get('axis', 1)
    builder.add_softmax_nd(
        name=node.name,
        input_name=node.inputs[0],
        output_name=node.outputs[0] + ('_softmax' if node.op_type == 'LogSoftmax' else ''),
        axis=axis
    )
    if node.op_type == 'LogSoftmax':
        builder.add_unary(
            name=node.name+'_log',
            input_name=node.outputs[0]+'_softmax',
            output_name=node.outputs[0],
            mode='log'
        )

mlmodel = convert(model="./distilbert-squad-128.onnx", target_ios="13",
                  custom_conversion_functions={'Softmax':_convert_softmax})
mlmodel.save('./converted.mlmodel')
```
