### ISSUE TITLE
Error when Converting Node Type Slice

### ISSUE THREAD

**Issue by jackkwok** [onnx/onnx-coreml#493]
## ❓Question

I got an error while converting ONNX model file to Core ML.  The error happens when converting "Node Type Slice".

The ONNX model was converted from a pretrained Pytorch yolov3 model that I downloaded from 
https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/weights/download_weights.sh

```
    batch_size = 1
    sample_input = torch.randn(batch_size, 3, opt.img_size, opt.img_size, requires_grad=True)
    # Export the model to ONNX
    torch.onnx.export(model,                     # model being run
                      sample_input,              # model input (or a tuple for multiple inputs)
                      onnx_file,                 # where to save the model
                      export_params=True,        # store the trained parameter weights inside the model file
                      # opset_version=10,          # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      verbose=True)
```

The error:

> 201/280: Converting Node Type Slice
> Traceback (most recent call last):
>   File "/Users/jkwok/anaconda3/envs/yolo/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/jkwok/anaconda3/envs/yolo/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/jkwok/src/nano/pytorch_yolov3/model_converter.py", line 73, in onnx_to_coreml
>     coreml_model = convert(onnx_file, target_ios='13')
>   File "/Users/jkwok/anaconda3/envs/yolo/lib/python3.6/site-packages/onnx_coreml/converter.py", line 621, in convert
>     _convert_node_nd(builder, node, graph, err)
>   File "/Users/jkwok/anaconda3/envs/yolo/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py", line 2363, in _convert_node_nd
>     return converter_fn(builder, node, graph, err)
>   File "/Users/jkwok/anaconda3/envs/yolo/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py", line 1937, in _convert_slice
>     return _convert_slice_ir4v9(builder, node, graph, err)
>   File "/Users/jkwok/anaconda3/envs/yolo/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py", line 1894, in _convert_slice_ir4v9
>     data_shape = graph.shape_dict[node.inputs[0]]
> KeyError: '655'

I tried targeting iOS 13.

Any suggestion on how to get around this error?

## System Information

My environment has these versions:
coremltools==3.0
onnx==1.5.0
onnx-coreml==1.0
onnxruntime==0.5.0
torch==1.2.0

**Comment by petersiemen** [comment]
I am facing the same problem while trying to convert the onnx model that I exported from 
https://github.com/ultralytics/xview-yolov3.

**Comment by bhushan23** [comment]
@jackkwok could you please attach the ONNX model?
It will be helpful

**Comment by petersiemen** [comment]
Hi,
please find the exported onnx model here:
https://drive.google.com/open?id=1XbbpLMy_vutfIKjLjWydb1ZycPmvOVqY
I use the https://github.com/ultralytics/yolov3 code to export the Darknet configured with the parameters in cfg/yolov3-tiny.cfg. In order to activate the export mode I just set ```ONNX_EXPORT = True``` in models.py:7

When trying to convert to coreml with this piece of code
```python
import onnx
from onnx_coreml import convert


model = onnx.load("export.onnx")
onnx.checker.check_model(model)
print(onnx.helper.printable_graph(reloaded.graph))

coreml_model = convert(
    model,
    target_ios="13",
    image_input_names=['input.1'], image_output_names=['187', '189']
)
coreml_model.save('export.mlmodel')
```
using
```
onnx-coreml==1.0
onnxmltools==1.5.1
```
and Python 3.7.4.




I run into an error that tells me that the "Slice" node (not sure yet  what this relates to in the original Pytorch model - but i will try to find it out today) cannot be converted.

This is the error that I get 

```bash
....
72/104: Converting Node Type Shape
73/104: Converting Node Type Slice
Traceback (most recent call last):
  File "/home/peter/workspace/pytorch-to-coreml/yolo_to_coreml.py", line 14, in <module>
    image_input_names=['input.1'], image_output_names=['187', '189']
  File "/home/peter/workspace/pytorch-to-coreml/.venv/lib/python3.7/site-packages/onnx_coreml/converter.py", line 621, in convert
    _convert_node_nd(builder, node, graph, err)
  File "/home/peter/workspace/pytorch-to-coreml/.venv/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 2363, in _convert_node_nd
    return converter_fn(builder, node, graph, err)
  File "/home/peter/workspace/pytorch-to-coreml/.venv/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 1937, in _convert_slice
    return _convert_slice_ir4v9(builder, node, graph, err)
  File "/home/peter/workspace/pytorch-to-coreml/.venv/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 1894, in _convert_slice_ir4v9
    data_shape = graph.shape_dict[node.inputs[0]]
KeyError: '152'

Process finished with exit code 1
```

Thanks a lot in advance for your help.

Peter

**Comment by petersiemen** [comment]
I found what causes the aforementioned problem. 
It seems that the intermediate processing graph does not find any input nodes for to be converted `torch.nn.Upsample`  nodes. 

I can reproduce the error with 
```python
import torch.nn as nn
import torch
import onnx
import torch.onnx
from onnx_coreml import convert


class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()

        self.conv = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, stride=1, padding=1)
        self.upsample = nn.Upsample(scale_factor=2)

    def forward(self, x):
        x = self.conv(x)
        x = self.upsample(x)
        return x


def test_convert_upsample():
    net = Network()
    x = torch.randn(1, 3, 416, 416, requires_grad=True)
    out = net(x)
    torch.onnx.export(net, x, "upsample.onnx")
    onnx_model = onnx.load("upsample.onnx")

    print(onnx.helper.printable_graph(onnx_model.graph))
    coreml_model = convert(
        onnx_model,
        target_ios="13"
    )
    coreml_model.save('upsample.mlmodel')
```

Which gives 
```

test_reproduce_upsampling_conversion_bug.py:20 (test_convert_upsample)
def test_convert_upsample():
        net = Network()
        x = torch.randn(1, 3, 416, 416, requires_grad=True)
        out = net(x)
        torch.onnx.export(net, x, "upsample.onnx")
        onnx_model = onnx.load("upsample.onnx")
    
        print(onnx.helper.printable_graph(onnx_model.graph))
        coreml_model = convert(
            onnx_model,
>           target_ios="13"
        )

test_reproduce_upsampling_conversion_bug.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../.venv/lib/python3.6/site-packages/onnx_coreml/converter.py:621: in convert
    _convert_node_nd(builder, node, graph, err)
../.venv/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py:2363: in _convert_node_nd
    return converter_fn(builder, node, graph, err)
../.venv/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py:1937: in _convert_slice
    return _convert_slice_ir4v9(builder, node, graph, err)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

builder = <coremltools.models.neural_network.builder.NeuralNetworkBuilder object at 0x7fda9191eef0>
node = <onnx_coreml._graph.Node object at 0x7fda918b5860>
graph = <onnx_coreml._graph.Graph object at 0x7fda9191efd0>
err = <onnx_coreml._error_utils.ErrorHandling object at 0x7fda9192ecf8>

    def _convert_slice_ir4v9(builder, node, graph, err):
        '''
        convert to CoreML Slice Static Layer:
        https://github.com/apple/coremltools/blob/655b3be5cc0d42c3c4fa49f0f0e4a93a26b3e492/mlmodel/format/NeuralNetwork.proto#L5082
        '''
>       data_shape = graph.shape_dict[node.inputs[0]]
E       KeyError: '25'

../.venv/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py:1894: KeyError
```

**SOLUTION:**
As a workaround I use a custom implementation as Upsampling Layer in my network.
```python
class UpsampleLayer(nn.Module):
    def __init__(self, scale_factor):
        super(UpsampleLayer, self).__init__()
        self.scale_factor = scale_factor

    def forward(self, x):
        assert (x.data.dim() == 4)
        B = x.data.size(0)
        C = x.data.size(1)
        H = x.data.size(2)
        W = x.data.size(3)
        ws = self.scale_factor
        hs = self.scale_factor
        x = x.view(B, C, H, 1, W, 1).expand(B, C, H, hs, W, ws).contiguous().view(B, C, H * hs, W * ws)
        return x


class NetworkWithCustomUpsample(nn.Module):
    def __init__(self):
        super(NetworkWithCustomUpsample, self).__init__()

        self.conv = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, stride=1, padding=1)
        self.upsample = UpsampleLayer(scale_factor=2)

    def forward(self, x):
        x = self.conv(x)
        x = self.upsample(x)
        return x

def test_convert_custom_upsample():
    net = NetworkWithCustomUpsample()
    x = torch.randn(1, 3, 416, 416, requires_grad=True)
    out = net(x)
    torch.onnx.export(net, x, "upsample.onnx")
    onnx_model = onnx.load("upsample.onnx")

    print(onnx.helper.printable_graph(onnx_model.graph))
    coreml_model = convert(
        onnx_model,
        target_ios="13"
    )
    coreml_model.save('upsample.mlmodel')
```

**Comment by bhushan23** [comment]
@petersiemen using custom UpSample is nice workaround.
@jackkwok another work around is to pass `size` to Upsample/interpolate in PyTorch instead of passing `scale` 
PyTorch to ONNX export does expand to few nodes when scale is passed and does feeds scale if output size is passed 
https://github.com/pytorch/pytorch/issues/27376 
Until, this is fixed, I would recommend to using `size` in pytorch.

For `Slice` layer, this PR https://github.com/onnx/onnx-coreml/pull/495 will resolve issue by checking rank of the input

**Comment by petersiemen** [comment]
Nice. Thanks for the detailed reply @bhushan23 . I think I will go with my custom layer for now. If I wanted to use the size parameter of torch.nnUpsample the network would need to know (pass down) the absolute size of the tensor that should be upsampled. 
But good to see that this fix will likely make it into the 1.1 release

**Comment by bhushan23** [comment]
closing this issue considering with `slice` change being in.
UpSample issue will be fixed in PyTorch -> ONNX path

**Comment by robotrovsky** [comment]
@petersiemen when i use your custom UpsampleLayer it converts fine to mlmodel. But during inference i get an error:
```
[Espresso::handle_ex_plan] exception=Invalid rank: 6
[Exception from Layer: 173: Expand_180]
```
This layer is shown as a broadcastToStatic layer in Netron. Do you have an idea why it throws this error?

**Comment by robotrovsky** [comment]
Reducing the rank to 5 and ignoring the batch size works for expand on the iphone.

        x = x.squeeze(0)
        x = x.view(C, H, 1, W, 1).expand( C, H, hs, W, ws).contiguous().view(C, H * hs, W * ws)
        x = x.unsqueeze(0)

**Comment by dlawrences** [comment]
> Reducing the rank to 5 and ignoring the batch size works for expand on the iphone.
> 
> ```
>     x = x.squeeze(0)
>     x = x.view(C, H, 1, W, 1).expand( C, H, hs, W, ws).contiguous().view(C, H * hs, W * ws)
>     x = x.unsqueeze(0)
> ```

I have taken another approach to avoid rank 6 tensors while still achieving the same desired computation:

```
# coreml does not support tensors of rank 6, so expanding by scale factor has to be done in 2 steps
x = x.view(B, C, H, 1, W).expand(B, C, H, hs, W).contiguous().view(B, C, H * hs, W)
# tensor is now temporarily of shape B, C, H * hs, W
x = x.view(B, C, H * hs, W, 1).expand(B, C, H * hs, W, ws).contiguous().view(B, C, H * hs, W * ws)
# tensor has final shape of B, C, H * hs, W * ws
return x
```
