### ISSUE TITLE
softmax nd inferes axis incorrectly in case of target_ios!='13'

### ISSUE THREAD

**Issue by vladserkoff** [onnx/onnx-coreml#497]
## 🐞Describe the bug
When the model uses softmax_nd, the axis is inferred incorrectly when the target is 11.2 and 12, but correctly in 13.
## To Reproduce
Unfortunately, I couldn't provide reproducible example, but I'll show the results I get.
I'm using the variation of ssd provided in this repo, and there's a sofmax applied along the 2 axis:
https://github.com/qfgaohao/pytorch-ssd/blob/382723c499fb9ab9ed13a47e18723c4182db75b1/vision/ssd/ssd.py#L91

I first convert the model to ONNX
`%scores : Float(1, 3000, 2) = onnx::Softmax[axis=2](%372)`

Then to convert the onnx model to coreml as described in the following comment: https://github.com/onnx/onnx-coreml/issues/478#issuecomment-539255349
The output is correct:
```
preds = coreml_model.predict(input_dict, useCPUOnly=True)['scores']
preds
array([[[9.9263489e-01, 7.3651006e-03],
        [9.9934018e-01, 6.5985508e-04],
        [9.9833399e-01, 1.6659620e-03],
        ...,
```
But when I change the `target_ios` to something less than '13' the softmax applies along the wrong axis:
```
preds = coreml_model.predict(input_dict, useCPUOnly=True)['scores']
preds
array([[[[[4.8325666e-11, 1.4698380e-04],
          [1.4702144e-10, 3.9794075e-05],
          [9.2687420e-11, 6.3403393e-05],
          ...,
```
My current solution is to add 1 to `axis` in the `_convert_softmax` function as follows:
```
def _convert_softmax(builder, node, graph, err):
    '''
    convert to CoreML SoftMax ND Layer:
    https://github.com/apple/coremltools/blob/655b3be5cc0d42c3c4fa49f0f0e4a93a26b3e492/mlmodel/format/NeuralNetwork.proto#3547
    '''
    axis = node.attrs.get('axis', 1) + 1
    builder.add_softmax_nd(
        name=node.name,
        input_name=node.inputs[0],
        output_name=node.outputs[0] + ('_softmax' if node.op_type == 'LogSoftmax' else ''),
        axis=axis
    )
    if node.op_type == 'LogSoftmax':
        builder.add_unary(
            name=node.name+'_log',
            input_name=node.outputs[0]+'_softmax',
            output_name=node.outputs[0],
            mode='log'
        )
```
This fixes the issue for me.

## System environment (please complete the following information):
 - coremltools==3.0
 - onnx-coreml==1.0
 - MacOS Catalina
 - How you install python - anaconda
 - python==3.7

**Comment by bhushan23** [comment]
@vladserkoff could you please share your generated mlmodel?
when `target_ios` is less than 13, we use CoreML 2 where SoftmaxND is not supported and we use old softmax layer which is applicable only on -3 axis. For your case, we need to transpose the input to ensure softmax is applied on desired axis and also need to squeeze/unsqueeze the input and output as necessart

**Comment by vladserkoff** [comment]
@bhushan23, which model do you want me to share, ios 13 or 12?

**Comment by bhushan23** [comment]
@vladserkoff 12 broken and fixed.

**Comment by vladserkoff** [comment]
@bhushan23, here you go

[mlmodels.zip](https://github.com/onnx/onnx-coreml/files/3749349/mlmodels.zip)

**Comment by bhushan23** [comment]
@vladserkoff could you please give try to onnx-coreml 1.1? 
we do have added softmax old layer if we know the shape
Meanwhile will change mlmodel output difference

**Comment by vladserkoff** [comment]
@bhushan23, sorry for taking so long. With the version 1.2 the model exports and compiles w/o any issues. But when I try to predict with this model I still get
```
RuntimeError: {
    NSLocalizedDescription = "Failed to evaluate model 0 in pipeline";
    NSUnderlyingError = "Error Domain=com.apple.CoreML Code=0 \"Error computing NN outputs.\" UserInfo={NSLocalizedDescription=Error computing NN outputs.}";
}
```
Currently I'm settled on this hack-y workaround for a binary task:
```python
def coreml_softmax(tensor: torch.Tensor) -> torch.Tensor:
    """
    iOS 12 compatible softmax for binary tasks.
    """
    tensor = (tensor[..., 1] - tensor[..., 0]).sigmoid()
    return tensor.unsqueeze(2)
```

**Comment by vladserkoff** [comment]
Okay, I've been able to find a better workaround, here I've assembled a minimal example. Not sure if it's onnx_coreml fault in the end.
```python
import torch
import onnx
import onnx_coreml

print(torch.__version__)
print(onnx.__version__)
print(onnx_coreml.__version__)

class BadNet(torch.nn.Module):
    def forward(self, x):
        return x.transpose(1, 2).softmax(1).transpose(2, 1)

class GoodNet(torch.nn.Module):
    def forward(self, x):
        orig_shape = x.shape
        return x.reshape(-1, orig_shape[-1]).softmax(1).reshape(orig_shape)
    
net = FailNet().eval()

x = torch.rand(2, 2, 2)
print(net(x))

torch.onnx.export(net,
                  x,
                  'test.onnx',
                  input_names=['input'],
                  output_names=['scores'],
                  opset_version=9)
onnx_model = onnx.load('test.onnx')

ssd_model = onnx_coreml.convert(onnx_model, minimum_ios_deployment_target='12')

input_dict = {'input': x.numpy()}
print(ssd_model.predict(input_dict))
```
BadNet will fail, and GoodNet won't obviously :)
In case of a 3D input, the workaround is to flatten the input into 2D, apply the softmax and then cast back to 3D.
