### ISSUE TITLE
ConvTranspose layer fails to convert. Provided number axes not supported 

### ISSUE THREAD

**Issue by tommymchugh** [onnx/onnx-coreml#503]
## 🐞Describe the bug
A clear and brief description of what the bug is.
Onnx conversion fails when trying to convert ConvTranspose Layer. Pytorch model works when exporting using other methods of export Pytorch offers such as TorchScript.

## Trace
If applicable, please paste the error trace.
1/11: Converting Node Type Gemm
2/11: Converting Node Type Relu
3/11: Converting Node Type Shape
4/11: Converting Node Type Gather
5/11: Converting Node Type Unsqueeze
6/11: Converting Node Type Concat
7/11: Converting Node Type Reshape
8/11: Converting Node Type ConvTranspose
Traceback (most recent call last):
  File "export_coreml.py", line 36, in <module>
    coreml_model = convert(model="onnx/model.onnx", target_ios='13')
  File "/Users/tommymchugh/Developer/Transpiction/env/lib/python3.6/site-packages/onnx_coreml/converter.py", line 625, in convert
    _convert_node_nd(builder, node, graph, err)
  File "/Users/tommymchugh/Developer/Transpiction/env/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py", line 2370, in _convert_node_nd
    return converter_fn(builder, node, graph, err)
  File "/Users/tommymchugh/Developer/Transpiction/env/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py", line 524, in _convert_conv
    builder, node, graph, err)
  File "/Users/tommymchugh/Developer/Transpiction/env/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py", line 70, in _add_conv_like_op
    return err.unsupported_op_configuration(builder, node, graph, "provided number axes {} not supported".format(rank))
  File "/Users/tommymchugh/Developer/Transpiction/env/lib/python3.6/site-packages/onnx_coreml/_error_utils.py", line 60, in unsupported_op_configuration
    self.rerun_suggestion)
TypeError: Error while converting op of type: ConvTranspose. Error message: provided number axes -1 not supported 
 Please try converting with higher target_ios.
You can also provide custom function/layer to convert the model.

## To Reproduce
- If a python script can reproduce the error, please paste the code snippet
```
from onnx_coreml import convert
import torch
import torch.nn as nn
import os
model = torch.load("model.pt", map_location=torch.device('cpu'))
scripted_model = torch.jit.script(model)
# Create a simple decoder class
class TofuDecoder(nn.Module):
    def __init__(self):
        super(TofuDecoder, self).__init__()
        self.tofu = model
        super(TofuDecoder, self).add_module("Tofu", self.tofu)
    
    def forward(self, input_layer):
        return self.tofu.decode(input_layer)

# Create random noise
device = torch.device("cpu")
noise = torch.randn(1, 100).to(device, dtype=torch.float)

decoder = TofuDecoder()
decoder = decoder.to(device)

torch.onnx.export(decoder, 
                noise, 
                "onnx/model.onnx", 
                input_names=["latent_vector"],
                output_names=["image"])

coreml_model = convert(model="onnx/model.onnx", target_ios='13')
```
- If applicable, please attach ONNX model
    - If model cannot be shared publicly, please attach it via filing a bug report at https://developer.apple.com/bug-reporting/ 
- If model conversion succeeds, however, there is numerical mismatch between the original and the coreml model, please paste python script used for comparison (pytorch code, onnx runtime code etc.)

## System environment (please complete the following information):
 - coremltools version  (e.g., 3.0b5): 3.0b6
 - onnx-coreml version (e.g. 1.0b2): 1.0b3
 - OS (e.g., MacOS, Linux): MaxOS
 - macOS version (if applicable): 10.15
 - How you install python (anaconda, virtualenv, system): Virtualenv
 - python version (e.g. 3.7): 3.6.8
 - any other relevant information:

**Comment by bhushan23** [comment]
@tommymchugh is this resolved?

**Comment by tommymchugh** [comment]
Yup @bhushan23, Input tensor size was a dynamic size, needed to set the exact dimensions of the input.

**Comment by dragen1860** [comment]
@tommymchugh how to set the axact dimension of the input when convert from onnx to coreml? Thank you.
