### ISSUE TITLE
Is Onnx-coreml conversion taget_device= ios11.2 really mean Coreml V1 ?

### ISSUE THREAD

**Issue by hezhangsprinter** [onnx/onnx-coreml#505]
## ❓Question
Is Onnx-coreml conversion taget_device= ios11.2 really mean Coreml V1 ?
## System Information
Hi 
    I saw that  taget_device= ios11.2 means that it is converted coreml v1. But when you visualize the mlmodel  using the Netron. It said it is coreml v2. 
I am curious it is v1 or v2 ?

**Comment by bhushan23** [comment]
@hezhangsprinter yes
