### ISSUE TITLE
Some Reshape layers with 6 ranks in the network generated from Pytorch-onnx conversion. How do I fix this please? 

### ISSUE THREAD

**Issue by williamtong0228** [onnx/onnx-coreml#507]
Could not pass the conversion between Onnx and Core ML. Because in the previous conversion some 6 rank layers were generated. I am new to this and I could not find anyone who had the same problem. It's a super-resolution GAN network. I really appreciate your help if anyone could refer me some links to check. Thanks in advance. 

<img width="916" alt="Screenshot 2019-11-16 at 1 58 31 AM" src="https://user-images.githubusercontent.com/38699976/68964603-c2df3e80-0814-11ea-8f07-20637e2bfdcc.png">

Generator(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(9, 9), stride=(1, 1), padding=(4, 4))
    (1): PReLU(num_parameters=1)
  )
  (layer2): ResidualBlock(
    (conv2d_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (prelu): PReLU(num_parameters=1)
    (conv2d_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (layer3): ResidualBlock(
    (conv2d_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (prelu): PReLU(num_parameters=1)
    (conv2d_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (layer4): ResidualBlock(
    (conv2d_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (prelu): PReLU(num_parameters=1)
    (conv2d_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (layer5): ResidualBlock(
    (conv2d_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (prelu): PReLU(num_parameters=1)
    (conv2d_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (layer6): ResidualBlock(
    (conv2d_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (prelu): PReLU(num_parameters=1)
    (conv2d_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (layer7): Sequential(
    (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (layer8): Sequential(
    (0): UpsampleBlock(
      (conv2d): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (pixel_shuffle): PixelShuffle(upscale_factor=2)
      (prelu): PReLU(num_parameters=1)
    )
    (1): UpsampleBlock(
      (conv2d): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (pixel_shuffle): PixelShuffle(upscale_factor=2)
      (prelu): PReLU(num_parameters=1)
    )
    (2): UpsampleBlock(
      (conv2d): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (pixel_shuffle): PixelShuffle(upscale_factor=2)
      (prelu): PReLU(num_parameters=1)
    )
    (3): Conv2d(64, 3, kernel_size=(9, 9), stride=(1, 1), padding=(4, 4))
  )
)

37/54: Converting Node Type Reshape
TypeError: Error while converting op of type: Reshape. Error message: Tensors more than rank 4 are not supported 
 Please try converting with higher target_ios.
You can also provide custom function/layer to convert the model.

**Comment by aseemw** [comment]
A few of these patterns have been handled by transforming the rank 6 patterns into less than rank 6 layers via graph transformations, prior to running the layer translation loop. 

See the tests here: https://github.com/onnx/onnx-coreml/blob/1da82bba8bf43cb4bda5f21ebdc4f09713a254d7/tests/pytorch_model_test.py#L470

here is the transformation: https://github.com/onnx/onnx-coreml/blob/1da82bba8bf43cb4bda5f21ebdc4f09713a254d7/onnx_coreml/_transformers.py#L326

Is the pattern in your model one of the test ones?

**Comment by williamtong0228** [comment]
Thank you so much aseemw. Really appreciate your help. I didn't know that code. It looks pretty like what I was missing. I am new to machine learning and Pytorch lol. I will figure it out how to implement it.
