### ISSUE TITLE
How to convert MultiArray to image as input type 

### ISSUE THREAD

**Issue by MarcSteven** [onnx/onnx-coreml#515]
## ❓Question
How to convert MultiArray to Image as input type 
## System Information
- If applicable

**Comment by AnasArram** [comment]
> ## ❓Question
> How to convert MultiArray to Image as input type
> 
> ## System Information
> * If applicable

you need to pass the input name (image_input_names) as an argument as follow:
coreml_model = convert(model, target_ios='13', custom_conversion_functions={'Upsample': _convert_upsample}, image_input_names = ['input']
replace  'input' with your model input name

**Comment by MarcSteven** [comment]
@AnasArram  Thank you so much, can you show a whole example about it?

**Comment by MarcSteven** [comment]
`#//
#//  convert_input_to_image.py
#//  AntsFaceDemo
#//
#//  Created by Marc Zhao on 2019/12/12.
#//  Copyright © 2019 AntsNetwork. All rights reserved.
#//

import coremltools
import coremltools.proto.FeatureTypes_pb2 as ft


spec = coremltools.utils.load_spec("FacialExpressionAnalysis.mlmodel") #please change the file name you are using 

input = spec.description.input[0]
input.type.imageType.colorSpace  = ft.ImageFeatureType.RGB
input.type.imageType.height = 224
input.type.imageType.width = 224

coremltools.utils.save_spec(spec,"FacialExpressionAnalysis.mlmodel")#Please change the file name using your own
`
This is all the solutions, but you must ensure the channel is 3, you can convert multiArray to image if you want.

**Comment by yonggunlee** [comment]
Hello, I don't know if this is still on going or not, but I have a question.
I see how we can change input&output type in coremltools.
I wonder if it can be happen in onnxmltools as well.
I have onnx model that takes [batchsize, img channel, img H, img W] which is multi array,
I also wish to change the input as image input as above question.
Can someone help me on it? I was trying to check inside of onnxmltools, but haven't found how.
