### ISSUE TITLE
Supply onnx_coreml.__version__

### ISSUE THREAD

**Issue by kossnick** [onnx/onnx-coreml#522]
## 🌱 Describe your Feature Request
Many Python modules supply a `.__version__` attribute, so you can query which version of it you're using. However, if in Python you do:
```
import onnx_coreml
dir(onnx_coreml)
print(onnx_coreml.__version__)
```
You will see there's no version available. It would be great to be able to query the version.

## Use cases
We have a complex conda environment to manage all the conda dependencies for exporting, and some machines (eg: CI systems) still run with the old library version on a lower velocity conda environment. If I could query the version, I could have an if/else block around calling the library (using the new vs old API).

## Describe alternatives you've considered
My current workaround is a try/catch block around the convert call, one attempting it with the new API, and falling back to the old API. This satisfies our latest exporting environment as well as our model stable CI conda environment.

**Comment by bhushan23** [comment]
Thanks @kossnick will look into this
