### ISSUE TITLE
Issues importing onnx_coreml 1.2

### ISSUE THREAD

**Issue by leonardoaraujosantos** [onnx/onnx-coreml#540]
## 🐞Describe the bug
Hi guys, I'm having issues importing onnx_coreml, I'm having this error related to remove_disconnected_layers

## Trace
```bash
ImportError                               Traceback (most recent call last)
<ipython-input-1-c97ee97e51cc> in <module>
----> 1 import onnx_coreml

~/anaconda3/lib/python3.7/site-packages/onnx_coreml/__init__.py in <module>
      4 from __future__ import unicode_literals
      5 
----> 6 from .converter import convert
      7 
      8 # onnx-coreml version

~/anaconda3/lib/python3.7/site-packages/onnx_coreml/converter.py in <module>
     33 
     34 # ML model passes
---> 35 from coremltools.converters.nnssa.coreml.graph_pass.mlmodel_passes import remove_disconnected_layers, transform_conv_crop
     36 
     37 from ._error_utils import ErrorHandling

ImportError: cannot import name 'remove_disconnected_layers' from 'coremltools.converters.nnssa.coreml.graph_pass.mlmodel_passes' (/Users/leonardo_a/anaconda3/lib/python3.7/site-packages/coremltools/converters/nnssa/coreml/graph_pass/mlmodel_passes.py)
```

## To Reproduce
- If a python script can reproduce the error, please paste the code snippet
```
import onnx_coreml
```

## System environment (please complete the following information):
 - coremltools version  (e.g., 3.0b5):3.1
 - onnx-coreml version (e.g. 1.0b2):1.2
 - OS (e.g., MacOS, Linux):Linux
 - macOS version (if applicable):
 - How you install python (anaconda, virtualenv, system):pip
 - python version (e.g. 3.7):3.7
 - any other relevant information:

**Comment by bhushan23** [comment]
You should be on coremltools version 3.2 @leonardoaraujosantos

**Comment by leonardoaraujosantos** [comment]
Thanks @bhushan23 it works perfectly.

**Comment by skliarovartem** [comment]
How to install v3.2? Im trying to pip3 install -Iv coremltools==3.2 but it doesn't work (I have python 3.8) I also tried to use Python 3.6 but still no luck...

**Comment by eric573** [comment]
Hi I face similar issues with installing the older version of coremltools as well. Any tips on solving this? Appreciate the help! :)

**Comment by skliarovartem** [comment]
yes, use Python 2.7 to solve it

**Comment by burgalon** [comment]
@bhushan23  Don't we want to support coreml 4.1+ ?
Right now I've been successfully able to install coremltools=3.2 and port a Pytorch neural network through Onnx to CoreML and deploy to device. However when trying to run an MLUpdateTask for personalizing model on device I get an error ` Model specification version field missing or corrupt`

Also noticed this commit which might be [related](https://github.com/apple/coremltools/commit/040b3e4054d54fc3d266aa6cf631a7895ee6a834) 

The error which I'm getting:
```
ModuleNotFoundError: No module named 'coremltools.converters.nnssa'
```

**Comment by burgalon** [comment]
okay... found out that coremltools 4.2 now goes directly from Pytorch to coreml, and so onnx is not necessary
