### ISSUE TITLE
Add support for MaxPool ceil_mode=1

### ISSUE THREAD

**Issue by Andrea-Scuderi** [onnx/onnx-coreml#573]
## 🌱 Describe your Feature Request
Model converted to onnx from Pytorch with `opset_version=12` are not supported
when they contain `MaxPool` `ceil_mode=1`  

- CoreML / iOS version you are using?
CoreML 3

**Comment by clementabary** [comment]
I'd like that feature as well. I think it appeared in `4.0b1` now

**Comment by Andrea-Scuderi** [comment]
@clementabary Yes, I confirm it works with `coremltools` https://coremltools.readme.io/docs
