### ISSUE TITLE
the link of the example of onnx to coreml is missing.

### ISSUE THREAD

**Issue by Guanbin-Huang** [onnx/onnx-coreml#580]
## System Information
- If applicable

**Comment by mohitnihalani** [comment]
You can check here [https://coremltools.readme.io/docs/onnx-conversion](https://coremltools.readme.io/docs/onnx-conversion) .Onnx-Coreml is now under Core-ML tools.

**Comment by DawerG** [comment]
As @mohitnihalani mentioned, please read the [onnx-conversion section](https://coremltools.readme.io/docs/onnx-conversion) in coremltools documentation. It contains the links for Jupyter notebooks containing reference examples. Thanks @mohitnihalani 

For future issues, engagements, bug-fixes and requests, please use [`coremltools`](https://github.com/apple/coremltools) GitHub repository. 

Closing it.
