### ISSUE TITLE
ImageScaler is not supported when converting to coreml.

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx-coreml#9]
When converting onnx model to coreml (tinyyolo), ImageScaler could not be supported.

**Comment by aseemw** [comment]
Yes this needs to be added. Can you provide the tinyyolo .onnx model as a test case? 
However, the same functionality can also be achieved by providing the "preprocessing_args" to the convert function, if the scaling is applied to the input and not in the middle of the graph.

**Comment by aseemw** [comment]
see PR #228
