### ISSUE TITLE
PyTorch to CoreML: incorrect input type

### ISSUE THREAD

**Issue by QuentinLEMAIRE** [onnx/onnx-coreml#92]
Hello, 

I am trying to run my PyTorch network on an iOS device. However, I face the issue of an incorrect input format when I put my network in Apple's demo (https://developer.apple.com/documentation/vision/classifying_images_with_vision_and_core_ml), my input is a MultiArray (Double 3 x 224 x 224) and the one used by Apple is Image (Color 224 x 224).

I didn't find a way to get an input Image with all the research I have done. To convert my network to .mlmodel, I save it as a .onnx with torch.onnx._export and then I use this library.

I found some solutions on the internet saying to put this parameter: `image_input_names='input'` but it didn't work and I don't find a way to get the correct input type. 

Do you have some ideas about how to do this?

Thank you!

**Comment by aseemw** [comment]
Make sure `image_input_names='input'` is a list and that the name you put matches the input name that you have in the model. It would be the same as the one you are getting in the Multiarray version of the .mlmodel that you now have. 

That is, lets say the input name is "input_image", then you would pass
`image_input_names=['input_image']` while calling convert.

**Comment by QuentinLEMAIRE** [comment]
Thank you, it works!
